/**
 * TL-PAGE-FORCLINICS-001 — /for-clinics
 *
 * Generated by scripts/make-placeholder-pages.mjs.
 *
 * Deliberately not a mock-up. See src/components/shell/not-built-yet.tsx for
 * why a fake search box or placeholder article list is worse than an honest
 * empty page on a health platform.
 */

import type { Metadata } from 'next';
import { NotBuiltYet } from '@/components/shell/not-built-yet';

export const metadata: Metadata = {
  title: "For clinics and hospitals",
  description: "Manage a multi-location dental practice: branches, staff, services and appointments.",
  // Not indexed while it has no content: an indexed empty page is a doorway
  // page, and it would rank for queries it cannot answer.
  robots: { index: false, follow: true },
};

export default function Page() {
  return (
    <NotBuiltYet
      title={"For clinics"}
      description={"Multi-location practice management: branches, staff and roles, service catalogues, opening hours, appointment capacity and clinic-level verification."}
      phase={"Phase 3 — Dentist and Clinic Ecosystem"}
      alternatives={[{"href":"/account/organizations/new","label":"Create your organization"}]}
    />
  );
}
