-- TOOTHLOGY — MySQL baseline
--
-- The complete schema, created from empty. This replaces the six PostgreSQL
-- migrations that preceded it; they remain in git history (last present at
-- commit ddedfdc) and were never applied to any persistent database — the
-- production deployment has never had a database connected.
--
-- Generated by `prisma migrate diff --from-empty`, then edited in exactly two
-- ways, both deliberate and both guarded by tests/platform/migrations.test.ts:
--
-- 1. TABLE COLLATION IS utf8mb4_bin, NOT utf8mb4_unicode_ci.
--    Prisma emits the case- and accent-insensitive collation. Under it, two
--    session-token hashes that differ only in letter case compare EQUAL (the
--    hashes are base64url, so case is significant), and "José" collides with
--    "Jose" in a unique index. Binary collation keeps the byte-exact comparison
--    the PostgreSQL schema had.
--
-- 2. THE THREE SEARCHABLE COLUMNS ARE utf8mb4_unicode_ci.
--    A FULLTEXT index over a binary collation is case-sensitive, so a patient
--    typing "implant" would not find "Implant". The PostgreSQL search lowered
--    everything through to_tsvector; a case-insensitive collation on just these
--    columns keeps that. They are not unique keys, so it costs nothing.
--
-- Nothing here depends on a MySQL extension, a trigger, a stored routine or a
-- server setting a shared host would not let you change.

-- CreateTable
CREATE TABLE `users` (
    `id` VARCHAR(191) NOT NULL,
    `email` VARCHAR(320) NULL,
    `phone` VARCHAR(191) NULL,
    `displayName` TEXT NULL,
    `emailVerifiedAt` DATETIME(3) NULL,
    `phoneVerifiedAt` DATETIME(3) NULL,
    `status` ENUM('ACTIVE', 'SUSPENDED', 'DEACTIVATED') NOT NULL DEFAULT 'ACTIVE',
    `locale` VARCHAR(191) NULL,
    `countryCode` VARCHAR(191) NULL,
    `timezone` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    UNIQUE INDEX `users_email_key`(`email`),
    UNIQUE INDEX `users_phone_key`(`phone`),
    INDEX `users_status_idx`(`status`),
    INDEX `users_createdAt_idx`(`createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `credentials` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `type` ENUM('PASSWORD', 'OTP_EMAIL', 'OTP_PHONE', 'TOTP', 'FEDERATED') NOT NULL,
    `secretHash` VARCHAR(191) NOT NULL,
    `externalId` VARCHAR(191) NULL,
    `provider` VARCHAR(191) NULL,
    `attemptsRemaining` INTEGER NULL,
    `expiresAt` DATETIME(3) NULL,
    `lastUsedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `credentials_externalId_idx`(`externalId`),
    UNIQUE INDEX `credentials_userId_type_provider_key`(`userId`, `type`, `provider`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `sessions` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `tokenHash` VARCHAR(191) NOT NULL,
    `ipAddress` VARCHAR(191) NULL,
    `userAgent` TEXT NULL,
    `expiresAt` DATETIME(3) NOT NULL,
    `revokedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `lastActiveAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `sessions_tokenHash_key`(`tokenHash`),
    INDEX `sessions_userId_revokedAt_idx`(`userId`, `revokedAt`),
    INDEX `sessions_expiresAt_idx`(`expiresAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `role_assignments` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `roleKey` VARCHAR(191) NOT NULL,
    `organizationId` VARCHAR(191) NULL,
    `expiresAt` DATETIME(3) NULL,
    `grantedByUserId` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `role_assignments_organizationId_idx`(`organizationId`),
    UNIQUE INDEX `role_assignments_userId_roleKey_organizationId_key`(`userId`, `roleKey`, `organizationId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `organizations` (
    `id` VARCHAR(191) NOT NULL,
    `type` ENUM('CLINIC', 'HOSPITAL', 'COLLEGE', 'SUPPLIER', 'MANUFACTURER', 'DISTRIBUTOR', 'EMPLOYER', 'PLATFORM') NOT NULL,
    `name` TEXT NOT NULL,
    `slug` VARCHAR(191) NOT NULL,
    `countryCode` VARCHAR(191) NOT NULL,
    `timezone` VARCHAR(191) NOT NULL,
    `currency` VARCHAR(191) NOT NULL,
    `status` ENUM('PENDING', 'ACTIVE', 'SUSPENDED', 'CLOSED') NOT NULL DEFAULT 'PENDING',
    `verifiedAt` DATETIME(3) NULL,
    `verificationExpires` DATETIME(3) NULL,
    `addressId` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    UNIQUE INDEX `organizations_slug_key`(`slug`),
    UNIQUE INDEX `organizations_addressId_key`(`addressId`),
    INDEX `organizations_type_status_idx`(`type`, `status`),
    INDEX `organizations_countryCode_idx`(`countryCode`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `organization_members` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `organizationId` VARCHAR(191) NOT NULL,
    `roleKey` VARCHAR(191) NOT NULL,
    `title` TEXT NULL,
    `isPrimary` BOOLEAN NOT NULL DEFAULT false,
    `joinedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `leftAt` DATETIME(3) NULL,

    INDEX `organization_members_organizationId_leftAt_idx`(`organizationId`, `leftAt`),
    UNIQUE INDEX `organization_members_userId_organizationId_key`(`userId`, `organizationId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `profiles` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `type` ENUM('PATIENT', 'DENTIST', 'STUDENT', 'RESEARCHER', 'SUPPLIER', 'EMPLOYER', 'STAFF') NOT NULL,
    `displayName` TEXT NULL,
    `headline` TEXT NULL,
    `bio` TEXT NULL,
    `slug` VARCHAR(191) NULL,
    `isPublic` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    INDEX `profiles_type_isPublic_idx`(`type`, `isPublic`),
    UNIQUE INDEX `profiles_userId_type_key`(`userId`, `type`),
    UNIQUE INDEX `profiles_type_slug_key`(`type`, `slug`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `consents` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `purpose` ENUM('MARKETING_EMAIL', 'MARKETING_SMS', 'MARKETING_WHATSAPP', 'CLINICAL_DATA_SHARING', 'AI_TRAINING', 'ANALYTICS_TRACKING') NOT NULL,
    `grantedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `revokedAt` DATETIME(3) NULL,
    `policyVersion` VARCHAR(191) NOT NULL,
    `ipAddress` VARCHAR(191) NULL,

    INDEX `consents_userId_purpose_idx`(`userId`, `purpose`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `countries` (
    `code` CHAR(2) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `defaultCurrency` CHAR(3) NOT NULL,
    `defaultLocale` VARCHAR(191) NOT NULL,
    `defaultTimezone` VARCHAR(191) NOT NULL,
    `callingCode` VARCHAR(191) NOT NULL,
    `taxRegime` ENUM('GST', 'VAT', 'SALES_TAX', 'NONE') NOT NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT false,

    PRIMARY KEY (`code`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `regions` (
    `id` VARCHAR(191) NOT NULL,
    `countryCode` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `code` VARCHAR(191) NULL,

    UNIQUE INDEX `regions_countryCode_name_key`(`countryCode`, `name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `cities` (
    `id` VARCHAR(191) NOT NULL,
    `regionId` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `latitude` DECIMAL(9, 6) NULL,
    `longitude` DECIMAL(9, 6) NULL,

    INDEX `cities_latitude_longitude_idx`(`latitude`, `longitude`),
    UNIQUE INDEX `cities_regionId_name_key`(`regionId`, `name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `addresses` (
    `id` VARCHAR(191) NOT NULL,
    `lines` JSON NOT NULL,
    `cityId` VARCHAR(191) NULL,
    `locality` TEXT NULL,
    `regionName` TEXT NULL,
    `postalCode` VARCHAR(191) NULL,
    `countryCode` CHAR(2) NOT NULL,
    `components` JSON NULL,
    `latitude` DECIMAL(9, 6) NULL,
    `longitude` DECIMAL(9, 6) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    INDEX `addresses_countryCode_postalCode_idx`(`countryCode`, `postalCode`),
    INDEX `addresses_latitude_longitude_idx`(`latitude`, `longitude`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `audit_events` (
    `id` VARCHAR(191) NOT NULL,
    `action` VARCHAR(191) NOT NULL,
    `actor` VARCHAR(191) NOT NULL,
    `subject` VARCHAR(191) NOT NULL,
    `outcome` ENUM('SUCCESS', 'FAILURE', 'DENIED') NOT NULL,
    `requestId` VARCHAR(191) NULL,
    `organizationId` VARCHAR(191) NULL,
    `ipAddress` VARCHAR(191) NULL,
    `userAgent` TEXT NULL,
    `detail` JSON NULL,
    `occurredAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `audit_events_actor_occurredAt_idx`(`actor`, `occurredAt`),
    INDEX `audit_events_subject_occurredAt_idx`(`subject`, `occurredAt`),
    INDEX `audit_events_action_occurredAt_idx`(`action`, `occurredAt`),
    INDEX `audit_events_occurredAt_idx`(`occurredAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `outbox_events` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `payload` JSON NOT NULL,
    `requestId` VARCHAR(191) NULL,
    `actor` VARCHAR(191) NULL,
    `occurredAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `publishedAt` DATETIME(3) NULL,
    `attempts` INTEGER NOT NULL DEFAULT 0,
    `lastError` TEXT NULL,

    INDEX `outbox_events_publishedAt_occurredAt_idx`(`publishedAt`, `occurredAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `idempotency_records` (
    `id` VARCHAR(191) NOT NULL,
    `key` VARCHAR(191) NOT NULL,
    `fingerprint` VARCHAR(191) NOT NULL,
    `statusCode` INTEGER NOT NULL,
    `responseBody` JSON NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `expiresAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `idempotency_records_key_key`(`key`),
    INDEX `idempotency_records_expiresAt_idx`(`expiresAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `feature_flag_overrides` (
    `id` VARCHAR(191) NOT NULL,
    `key` VARCHAR(191) NOT NULL,
    `state` VARCHAR(191) NOT NULL,
    `reason` TEXT NULL,
    `setByUserId` VARCHAR(191) NULL,
    `expiresAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `feature_flag_overrides_key_key`(`key`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `file_objects` (
    `id` VARCHAR(191) NOT NULL,
    `storageKey` VARCHAR(512) NOT NULL,
    `contentType` VARCHAR(191) NOT NULL,
    `sizeBytes` INTEGER NOT NULL,
    `checksum` VARCHAR(191) NOT NULL,
    `sensitivity` ENUM('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'PHI') NOT NULL,
    `ownerUserId` VARCHAR(191) NULL,
    `ownerOrganizationId` VARCHAR(191) NULL,
    `originalFilename` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    UNIQUE INDEX `file_objects_storageKey_key`(`storageKey`),
    INDEX `file_objects_ownerUserId_deletedAt_idx`(`ownerUserId`, `deletedAt`),
    INDEX `file_objects_ownerOrganizationId_deletedAt_idx`(`ownerOrganizationId`, `deletedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `notification_preferences` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `channel` ENUM('IN_APP', 'PUSH', 'EMAIL', 'SMS', 'WHATSAPP') NOT NULL,
    `enabled` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `notification_preferences_userId_channel_key`(`userId`, `channel`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `verification_tokens` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `type` ENUM('EMAIL_VERIFICATION', 'PHONE_VERIFICATION', 'PASSWORD_RESET', 'MAGIC_LINK', 'ACTION_CONFIRMATION') NOT NULL,
    `tokenHash` VARCHAR(191) NOT NULL,
    `destination` VARCHAR(320) NOT NULL,
    `expiresAt` DATETIME(3) NOT NULL,
    `consumedAt` DATETIME(3) NULL,
    `ipAddress` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `verification_tokens_tokenHash_key`(`tokenHash`),
    INDEX `verification_tokens_userId_type_idx`(`userId`, `type`),
    INDEX `verification_tokens_expiresAt_idx`(`expiresAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `login_attempts` (
    `id` VARCHAR(191) NOT NULL,
    `identifier` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NULL,
    `success` BOOLEAN NOT NULL,
    `reason` TEXT NULL,
    `ipAddress` VARCHAR(191) NULL,
    `userAgent` TEXT NULL,
    `occurredAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `login_attempts_identifier_occurredAt_idx`(`identifier`, `occurredAt`),
    INDEX `login_attempts_ipAddress_occurredAt_idx`(`ipAddress`, `occurredAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `rate_limit_counters` (
    `key` VARCHAR(191) NOT NULL,
    `count` INTEGER NOT NULL,
    `windowEndsAt` DATETIME(3) NOT NULL,

    INDEX `rate_limit_counters_windowEndsAt_idx`(`windowEndsAt`),
    PRIMARY KEY (`key`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `invitations` (
    `id` VARCHAR(191) NOT NULL,
    `organizationId` VARCHAR(191) NOT NULL,
    `email` VARCHAR(320) NOT NULL,
    `roleKey` VARCHAR(191) NOT NULL,
    `tokenHash` VARCHAR(191) NOT NULL,
    `status` ENUM('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED') NOT NULL DEFAULT 'PENDING',
    `invitedByUserId` VARCHAR(191) NOT NULL,
    `acceptedByUserId` VARCHAR(191) NULL,
    `expiresAt` DATETIME(3) NOT NULL,
    `acceptedAt` DATETIME(3) NULL,
    `revokedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `invitations_tokenHash_key`(`tokenHash`),
    INDEX `invitations_organizationId_status_idx`(`organizationId`, `status`),
    INDEX `invitations_email_status_idx`(`email`, `status`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `locations` (
    `id` VARCHAR(191) NOT NULL,
    `organizationId` VARCHAR(191) NOT NULL,
    `name` TEXT NOT NULL,
    `slug` VARCHAR(191) NOT NULL,
    `addressId` VARCHAR(191) NULL,
    `latitude` DECIMAL(9, 6) NULL,
    `longitude` DECIMAL(9, 6) NULL,
    `timezone` VARCHAR(191) NOT NULL,
    `phone` VARCHAR(191) NULL,
    `email` VARCHAR(320) NULL,
    `isPrimary` BOOLEAN NOT NULL DEFAULT false,
    `status` ENUM('ACTIVE', 'TEMPORARILY_CLOSED', 'PERMANENTLY_CLOSED') NOT NULL DEFAULT 'ACTIVE',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    UNIQUE INDEX `locations_addressId_key`(`addressId`),
    INDEX `locations_latitude_longitude_idx`(`latitude`, `longitude`),
    INDEX `locations_organizationId_status_idx`(`organizationId`, `status`),
    UNIQUE INDEX `locations_organizationId_slug_key`(`organizationId`, `slug`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `business_hours` (
    `id` VARCHAR(191) NOT NULL,
    `locationId` VARCHAR(191) NOT NULL,
    `dayOfWeek` INTEGER NOT NULL,
    `opensAtMinutes` INTEGER NOT NULL,
    `closesAtMinutes` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `business_hours_locationId_dayOfWeek_idx`(`locationId`, `dayOfWeek`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `holidays` (
    `id` VARCHAR(191) NOT NULL,
    `countryCode` CHAR(2) NOT NULL,
    `regionId` VARCHAR(191) NULL,
    `date` DATE NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `isPublic` BOOLEAN NOT NULL DEFAULT true,

    INDEX `holidays_countryCode_date_idx`(`countryCode`, `date`),
    UNIQUE INDEX `holidays_countryCode_regionId_date_name_key`(`countryCode`, `regionId`, `date`, `name`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `tax_configurations` (
    `id` VARCHAR(191) NOT NULL,
    `countryCode` CHAR(2) NOT NULL,
    `regime` ENUM('GST', 'VAT', 'SALES_TAX', 'NONE') NOT NULL,
    `rateBasisPoints` INTEGER NOT NULL,
    `category` VARCHAR(191) NOT NULL,
    `effectiveFrom` DATETIME(3) NOT NULL,
    `effectiveTo` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `tax_configurations_countryCode_category_effectiveFrom_idx`(`countryCode`, `category`, `effectiveFrom`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `translation_keys` (
    `id` VARCHAR(191) NOT NULL,
    `key` VARCHAR(191) NOT NULL,
    `description` TEXT NULL,
    `namespace` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `translation_keys_key_key`(`key`),
    INDEX `translation_keys_namespace_idx`(`namespace`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `translations` (
    `id` VARCHAR(191) NOT NULL,
    `keyId` VARCHAR(191) NOT NULL,
    `locale` VARCHAR(191) NOT NULL,
    `value` TEXT NOT NULL,
    `isMachineTranslated` BOOLEAN NOT NULL DEFAULT false,
    `reviewedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `translations_locale_idx`(`locale`),
    UNIQUE INDEX `translations_keyId_locale_key`(`keyId`, `locale`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `notification_templates` (
    `id` VARCHAR(191) NOT NULL,
    `notificationId` VARCHAR(191) NOT NULL,
    `channel` ENUM('IN_APP', 'PUSH', 'EMAIL', 'SMS', 'WHATSAPP') NOT NULL,
    `locale` VARCHAR(191) NOT NULL,
    `subject` TEXT NULL,
    `body` MEDIUMTEXT NOT NULL,
    `providerTemplateId` VARCHAR(191) NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `notification_templates_notificationId_channel_locale_key`(`notificationId`, `channel`, `locale`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `notification_records` (
    `id` VARCHAR(191) NOT NULL,
    `notificationId` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `channel` ENUM('IN_APP', 'PUSH', 'EMAIL', 'SMS', 'WHATSAPP') NOT NULL,
    `status` ENUM('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'SKIPPED') NOT NULL DEFAULT 'PENDING',
    `data` JSON NULL,
    `attempts` INTEGER NOT NULL DEFAULT 0,
    `lastError` TEXT NULL,
    `providerMessageId` VARCHAR(191) NULL,
    `nextAttemptAt` DATETIME(3) NULL,
    `sentAt` DATETIME(3) NULL,
    `deliveredAt` DATETIME(3) NULL,
    `failedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `notification_records_userId_createdAt_idx`(`userId`, `createdAt`),
    INDEX `notification_records_status_nextAttemptAt_idx`(`status`, `nextAttemptAt`),
    INDEX `notification_records_notificationId_createdAt_idx`(`notificationId`, `createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `in_app_notifications` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `notificationId` VARCHAR(191) NOT NULL,
    `title` TEXT NOT NULL,
    `body` TEXT NOT NULL,
    `linkUrl` TEXT NULL,
    `readAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `in_app_notifications_userId_readAt_createdAt_idx`(`userId`, `readAt`, `createdAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `saved_locations` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `label` TEXT NOT NULL,
    `addressId` VARCHAR(191) NULL,
    `latitude` DECIMAL(9, 6) NOT NULL,
    `longitude` DECIMAL(9, 6) NOT NULL,
    `isDefault` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `saved_locations_addressId_key`(`addressId`),
    INDEX `saved_locations_userId_idx`(`userId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `geofences` (
    `id` VARCHAR(191) NOT NULL,
    `name` TEXT NOT NULL,
    `kind` ENUM('RADIUS', 'POLYGON') NOT NULL,
    `centreLatitude` DECIMAL(9, 6) NULL,
    `centreLongitude` DECIMAL(9, 6) NULL,
    `radiusMetres` INTEGER NULL,
    `vertices` JSON NULL,
    `ownerType` VARCHAR(191) NOT NULL,
    `ownerId` VARCHAR(191) NOT NULL,
    `purpose` ENUM('SERVICE_AREA', 'CAMPAIGN', 'NOTIFICATION', 'FRAUD_SIGNAL', 'ATTENDANCE') NOT NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `geofences_ownerType_ownerId_idx`(`ownerType`, `ownerId`),
    INDEX `geofences_purpose_isActive_idx`(`purpose`, `isActive`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `search_documents` (
    `id` VARCHAR(191) NOT NULL,
    `entityType` VARCHAR(191) NOT NULL,
    `entityId` VARCHAR(191) NOT NULL,
    `title` TEXT COLLATE utf8mb4_unicode_ci NOT NULL,
    `summary` TEXT COLLATE utf8mb4_unicode_ci NULL,
    `body` MEDIUMTEXT COLLATE utf8mb4_unicode_ci NOT NULL,
    `facets` JSON NULL,
    `locale` VARCHAR(191) NOT NULL,
    `countryCode` CHAR(2) NULL,
    `latitude` DECIMAL(9, 6) NULL,
    `longitude` DECIMAL(9, 6) NULL,
    `qualityScore` DOUBLE NOT NULL DEFAULT 0,
    `isPublished` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `search_documents_entityType_isPublished_idx`(`entityType`, `isPublished`),
    INDEX `search_documents_latitude_longitude_idx`(`latitude`, `longitude`),
    INDEX `search_documents_qualityScore_idx`(`qualityScore`),
    UNIQUE INDEX `search_documents_entityType_entityId_key`(`entityType`, `entityId`),
    FULLTEXT INDEX `search_documents_text_ft`(`title`, `summary`, `body`),
    FULLTEXT INDEX `search_documents_title_ft`(`title`),
    FULLTEXT INDEX `search_documents_summary_ft`(`summary`),
    FULLTEXT INDEX `search_documents_body_ft`(`body`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `account_deletion_requests` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `reason` TEXT NULL,
    `requestedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `scheduledFor` DATETIME(3) NOT NULL,
    `status` ENUM('PENDING', 'CANCELLED', 'COMPLETED') NOT NULL DEFAULT 'PENDING',
    `cancelledAt` DATETIME(3) NULL,
    `completedAt` DATETIME(3) NULL,

    UNIQUE INDEX `account_deletion_requests_userId_key`(`userId`),
    INDEX `account_deletion_requests_status_scheduledFor_idx`(`status`, `scheduledFor`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `dentist_profiles` (
    `id` VARCHAR(191) NOT NULL,
    `userId` VARCHAR(191) NOT NULL,
    `slug` VARCHAR(191) NOT NULL,
    `headline` TEXT NULL,
    `bio` TEXT NULL,
    `practisingSince` INTEGER NULL,
    `languages` JSON NOT NULL,
    `consultationFeeMinor` INTEGER NULL,
    `consultationCurrency` VARCHAR(191) NULL,
    `gender` ENUM('FEMALE', 'MALE', 'OTHER', 'UNDISCLOSED') NULL,
    `status` ENUM('DRAFT', 'SUBMITTED', 'VERIFIED', 'REJECTED', 'SUSPENDED') NOT NULL DEFAULT 'DRAFT',
    `isVerified` BOOLEAN NOT NULL DEFAULT false,
    `verifiedAt` DATETIME(3) NULL,
    `verificationExpiresAt` DATETIME(3) NULL,
    `isDiscoverable` BOOLEAN NOT NULL DEFAULT false,
    `qualityScore` DOUBLE NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    UNIQUE INDEX `dentist_profiles_userId_key`(`userId`),
    UNIQUE INDEX `dentist_profiles_slug_key`(`slug`),
    INDEX `dentist_profiles_status_isDiscoverable_idx`(`status`, `isDiscoverable`),
    INDEX `dentist_profiles_isVerified_idx`(`isVerified`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `qualifications` (
    `id` VARCHAR(191) NOT NULL,
    `dentistProfileId` VARCHAR(191) NOT NULL,
    `degree` TEXT NOT NULL,
    `institution` TEXT NOT NULL,
    `year` INTEGER NOT NULL,
    `registrationNumber` TEXT NULL,
    `registrationBody` TEXT NULL,
    `isVerified` BOOLEAN NOT NULL DEFAULT false,
    `verifiedAt` DATETIME(3) NULL,
    `documentFileId` VARCHAR(191) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `qualifications_dentistProfileId_idx`(`dentistProfileId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `specialties` (
    `id` VARCHAR(191) NOT NULL,
    `key` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `description` TEXT NOT NULL,

    UNIQUE INDEX `specialties_key_key`(`key`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `dentist_specialties` (
    `id` VARCHAR(191) NOT NULL,
    `dentistProfileId` VARCHAR(191) NOT NULL,
    `specialtyId` VARCHAR(191) NOT NULL,
    `isPrimary` BOOLEAN NOT NULL DEFAULT false,

    UNIQUE INDEX `dentist_specialties_dentistProfileId_specialtyId_key`(`dentistProfileId`, `specialtyId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `dentist_practices` (
    `id` VARCHAR(191) NOT NULL,
    `dentistProfileId` VARCHAR(191) NOT NULL,
    `locationId` VARCHAR(191) NOT NULL,
    `isConfirmed` BOOLEAN NOT NULL DEFAULT false,
    `confirmedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `dentist_practices_locationId_isConfirmed_idx`(`locationId`, `isConfirmed`),
    UNIQUE INDEX `dentist_practices_dentistProfileId_locationId_key`(`dentistProfileId`, `locationId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `verification_requests` (
    `id` VARCHAR(191) NOT NULL,
    `subjectType` ENUM('DENTIST', 'ORGANIZATION') NOT NULL,
    `subjectId` VARCHAR(191) NOT NULL,
    `dentistProfileId` VARCHAR(191) NULL,
    `status` ENUM('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'REVOKED', 'EXPIRED') NOT NULL DEFAULT 'PENDING',
    `submittedEvidence` JSON NULL,
    `submittedByUserId` VARCHAR(191) NOT NULL,
    `submittedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `reviewedByUserId` VARCHAR(191) NULL,
    `reviewedAt` DATETIME(3) NULL,
    `decisionReason` TEXT NULL,
    `reviewerNotes` TEXT NULL,
    `expiresAt` DATETIME(3) NULL,
    `revokedAt` DATETIME(3) NULL,
    `revokedByUserId` VARCHAR(191) NULL,
    `revocationReason` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `verification_requests_subjectType_subjectId_status_idx`(`subjectType`, `subjectId`, `status`),
    INDEX `verification_requests_status_submittedAt_idx`(`status`, `submittedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `service_offerings` (
    `id` VARCHAR(191) NOT NULL,
    `locationId` VARCHAR(191) NOT NULL,
    `name` TEXT NOT NULL,
    `description` TEXT NULL,
    `priceMinor` INTEGER NULL,
    `currency` VARCHAR(191) NULL,
    `durationMinutes` INTEGER NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `service_offerings_locationId_isActive_idx`(`locationId`, `isActive`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `service_categories` (
    `id` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `slug` VARCHAR(191) NOT NULL,
    `description` TEXT NULL,
    `patientDescription` TEXT NULL,
    `sortOrder` INTEGER NOT NULL DEFAULT 0,
    `status` ENUM('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    UNIQUE INDEX `service_categories_slug_key`(`slug`),
    INDEX `service_categories_status_sortOrder_idx`(`status`, `sortOrder`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `catalogue_services` (
    `id` VARCHAR(191) NOT NULL,
    `categoryId` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `slug` VARCHAR(191) NOT NULL,
    `description` TEXT NULL,
    `shortDescription` TEXT NULL,
    `patientDescription` TEXT NULL,
    `defaultUnitId` VARCHAR(191) NULL,
    `suggestedMinMinor` BIGINT NULL,
    `suggestedMaxMinor` BIGINT NULL,
    `suggestedCurrency` VARCHAR(191) NULL,
    `suggestedIsOpenEnded` BOOLEAN NOT NULL DEFAULT false,
    `isCustomQuote` BOOLEAN NOT NULL DEFAULT false,
    `isPackage` BOOLEAN NOT NULL DEFAULT false,
    `sortOrder` INTEGER NOT NULL DEFAULT 0,
    `status` ENUM('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    UNIQUE INDEX `catalogue_services_slug_key`(`slug`),
    INDEX `catalogue_services_categoryId_status_sortOrder_idx`(`categoryId`, `status`, `sortOrder`),
    INDEX `catalogue_services_status_idx`(`status`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `service_category_links` (
    `id` VARCHAR(191) NOT NULL,
    `serviceId` VARCHAR(191) NOT NULL,
    `categoryId` VARCHAR(191) NOT NULL,
    `sortOrder` INTEGER NOT NULL DEFAULT 0,

    INDEX `service_category_links_categoryId_idx`(`categoryId`),
    UNIQUE INDEX `service_category_links_serviceId_categoryId_key`(`serviceId`, `categoryId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `service_variants` (
    `id` VARCHAR(191) NOT NULL,
    `serviceId` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `slug` VARCHAR(191) NOT NULL,
    `description` TEXT NULL,
    `shortDescription` TEXT NULL,
    `suggestedMinMinor` BIGINT NULL,
    `suggestedMaxMinor` BIGINT NULL,
    `suggestedCurrency` VARCHAR(191) NULL,
    `suggestedIsOpenEnded` BOOLEAN NOT NULL DEFAULT false,
    `isCustomQuote` BOOLEAN NOT NULL DEFAULT false,
    `sortOrder` INTEGER NOT NULL DEFAULT 0,
    `status` ENUM('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    INDEX `service_variants_serviceId_status_sortOrder_idx`(`serviceId`, `status`, `sortOrder`),
    UNIQUE INDEX `service_variants_serviceId_slug_key`(`serviceId`, `slug`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `service_synonyms` (
    `id` VARCHAR(191) NOT NULL,
    `serviceId` VARCHAR(191) NOT NULL,
    `keyword` TEXT NOT NULL,
    `normalized` VARCHAR(191) NOT NULL,

    INDEX `service_synonyms_normalized_idx`(`normalized`),
    UNIQUE INDEX `service_synonyms_serviceId_normalized_key`(`serviceId`, `normalized`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `price_units` (
    `id` VARCHAR(191) NOT NULL,
    `key` VARCHAR(191) NOT NULL,
    `name` VARCHAR(191) NOT NULL,
    `shortLabel` VARCHAR(191) NOT NULL,
    `sortOrder` INTEGER NOT NULL DEFAULT 0,
    `status` ENUM('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED') NOT NULL DEFAULT 'ACTIVE',
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `price_units_key_key`(`key`),
    INDEX `price_units_status_sortOrder_idx`(`status`, `sortOrder`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `dentist_service_prices` (
    `id` VARCHAR(191) NOT NULL,
    `dentistProfileId` VARCHAR(191) NOT NULL,
    `serviceId` VARCHAR(191) NOT NULL,
    `locationId` VARCHAR(191) NULL,
    `scopeKey` VARCHAR(191) NOT NULL,
    `isEnabled` BOOLEAN NOT NULL DEFAULT true,
    `isPublicVisible` BOOLEAN NOT NULL DEFAULT true,
    `note` TEXT NULL,
    `customDescription` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    INDEX `dentist_service_prices_dentistProfileId_isEnabled_idx`(`dentistProfileId`, `isEnabled`),
    INDEX `dentist_service_prices_locationId_isEnabled_idx`(`locationId`, `isEnabled`),
    INDEX `dentist_service_prices_serviceId_idx`(`serviceId`),
    UNIQUE INDEX `dentist_service_prices_dentistProfileId_serviceId_scopeKey_key`(`dentistProfileId`, `serviceId`, `scopeKey`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `dentist_variant_prices` (
    `id` VARCHAR(191) NOT NULL,
    `dentistServicePriceId` VARCHAR(191) NOT NULL,
    `variantId` VARCHAR(191) NULL,
    `variantKey` VARCHAR(191) NOT NULL,
    `unitId` VARCHAR(191) NOT NULL,
    `minMinor` BIGINT NULL,
    `maxMinor` BIGINT NULL,
    `actualMinor` BIGINT NULL,
    `discountedMinor` BIGINT NULL,
    `packageMinor` BIGINT NULL,
    `additionalMinor` BIGINT NULL,
    `currency` VARCHAR(191) NOT NULL,
    `isCustomQuote` BOOLEAN NOT NULL DEFAULT false,
    `isEnabled` BOOLEAN NOT NULL DEFAULT true,
    `customDescription` TEXT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `dentist_variant_prices_variantId_idx`(`variantId`),
    UNIQUE INDEX `dentist_variant_prices_dentistServicePriceId_variantKey_key`(`dentistServicePriceId`, `variantKey`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `dentist_packages` (
    `id` VARCHAR(191) NOT NULL,
    `dentistProfileId` VARCHAR(191) NOT NULL,
    `locationId` VARCHAR(191) NULL,
    `name` TEXT NOT NULL,
    `slug` VARCHAR(191) NOT NULL,
    `description` TEXT NULL,
    `terms` TEXT NULL,
    `priceMinor` BIGINT NOT NULL,
    `currency` VARCHAR(191) NOT NULL,
    `componentTotalMinor` BIGINT NULL,
    `validFrom` DATETIME(3) NULL,
    `validUntil` DATETIME(3) NULL,
    `status` ENUM('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT',
    `isPublicVisible` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,

    INDEX `dentist_packages_dentistProfileId_status_idx`(`dentistProfileId`, `status`),
    INDEX `dentist_packages_locationId_status_idx`(`locationId`, `status`),
    UNIQUE INDEX `dentist_packages_dentistProfileId_slug_key`(`dentistProfileId`, `slug`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `package_items` (
    `id` VARCHAR(191) NOT NULL,
    `packageId` VARCHAR(191) NOT NULL,
    `serviceId` VARCHAR(191) NOT NULL,
    `variantId` VARCHAR(191) NULL,
    `quantity` INTEGER NOT NULL DEFAULT 1,
    `isIncluded` BOOLEAN NOT NULL DEFAULT true,
    `note` TEXT NULL,
    `sortOrder` INTEGER NOT NULL DEFAULT 0,

    INDEX `package_items_packageId_sortOrder_idx`(`packageId`, `sortOrder`),
    INDEX `package_items_serviceId_idx`(`serviceId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- CreateTable
CREATE TABLE `price_history` (
    `id` VARCHAR(191) NOT NULL,
    `dentistServicePriceId` VARCHAR(191) NOT NULL,
    `dentistVariantPriceId` VARCHAR(191) NULL,
    `changedByUserId` VARCHAR(191) NOT NULL,
    `field` VARCHAR(191) NOT NULL,
    `previousMinor` BIGINT NULL,
    `newMinor` BIGINT NULL,
    `currency` VARCHAR(191) NULL,
    `previousText` TEXT NULL,
    `newText` TEXT NULL,
    `changedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `price_history_dentistServicePriceId_changedAt_idx`(`dentistServicePriceId`, `changedAt`),
    INDEX `price_history_dentistVariantPriceId_changedAt_idx`(`dentistVariantPriceId`, `changedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;

-- AddForeignKey
ALTER TABLE `credentials` ADD CONSTRAINT `credentials_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `sessions` ADD CONSTRAINT `sessions_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `role_assignments` ADD CONSTRAINT `role_assignments_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `role_assignments` ADD CONSTRAINT `role_assignments_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `organizations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `organizations` ADD CONSTRAINT `organizations_addressId_fkey` FOREIGN KEY (`addressId`) REFERENCES `addresses`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `organization_members` ADD CONSTRAINT `organization_members_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `organization_members` ADD CONSTRAINT `organization_members_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `organizations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `profiles` ADD CONSTRAINT `profiles_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `consents` ADD CONSTRAINT `consents_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `regions` ADD CONSTRAINT `regions_countryCode_fkey` FOREIGN KEY (`countryCode`) REFERENCES `countries`(`code`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `cities` ADD CONSTRAINT `cities_regionId_fkey` FOREIGN KEY (`regionId`) REFERENCES `regions`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `addresses` ADD CONSTRAINT `addresses_cityId_fkey` FOREIGN KEY (`cityId`) REFERENCES `cities`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `file_objects` ADD CONSTRAINT `file_objects_ownerUserId_fkey` FOREIGN KEY (`ownerUserId`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `notification_preferences` ADD CONSTRAINT `notification_preferences_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `verification_tokens` ADD CONSTRAINT `verification_tokens_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `invitations` ADD CONSTRAINT `invitations_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `organizations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `locations` ADD CONSTRAINT `locations_organizationId_fkey` FOREIGN KEY (`organizationId`) REFERENCES `organizations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `locations` ADD CONSTRAINT `locations_addressId_fkey` FOREIGN KEY (`addressId`) REFERENCES `addresses`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `business_hours` ADD CONSTRAINT `business_hours_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `locations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `translations` ADD CONSTRAINT `translations_keyId_fkey` FOREIGN KEY (`keyId`) REFERENCES `translation_keys`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `notification_records` ADD CONSTRAINT `notification_records_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `in_app_notifications` ADD CONSTRAINT `in_app_notifications_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `saved_locations` ADD CONSTRAINT `saved_locations_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `saved_locations` ADD CONSTRAINT `saved_locations_addressId_fkey` FOREIGN KEY (`addressId`) REFERENCES `addresses`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `account_deletion_requests` ADD CONSTRAINT `account_deletion_requests_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `dentist_profiles` ADD CONSTRAINT `dentist_profiles_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `qualifications` ADD CONSTRAINT `qualifications_dentistProfileId_fkey` FOREIGN KEY (`dentistProfileId`) REFERENCES `dentist_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `dentist_specialties` ADD CONSTRAINT `dentist_specialties_dentistProfileId_fkey` FOREIGN KEY (`dentistProfileId`) REFERENCES `dentist_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `dentist_specialties` ADD CONSTRAINT `dentist_specialties_specialtyId_fkey` FOREIGN KEY (`specialtyId`) REFERENCES `specialties`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `dentist_practices` ADD CONSTRAINT `dentist_practices_dentistProfileId_fkey` FOREIGN KEY (`dentistProfileId`) REFERENCES `dentist_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `dentist_practices` ADD CONSTRAINT `dentist_practices_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `locations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `verification_requests` ADD CONSTRAINT `verification_requests_dentistProfileId_fkey` FOREIGN KEY (`dentistProfileId`) REFERENCES `dentist_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `service_offerings` ADD CONSTRAINT `service_offerings_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `locations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `catalogue_services` ADD CONSTRAINT `catalogue_services_categoryId_fkey` FOREIGN KEY (`categoryId`) REFERENCES `service_categories`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `catalogue_services` ADD CONSTRAINT `catalogue_services_defaultUnitId_fkey` FOREIGN KEY (`defaultUnitId`) REFERENCES `price_units`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `service_category_links` ADD CONSTRAINT `service_category_links_serviceId_fkey` FOREIGN KEY (`serviceId`) REFERENCES `catalogue_services`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `service_category_links` ADD CONSTRAINT `service_category_links_categoryId_fkey` FOREIGN KEY (`categoryId`) REFERENCES `service_categories`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `service_variants` ADD CONSTRAINT `service_variants_serviceId_fkey` FOREIGN KEY (`serviceId`) REFERENCES `catalogue_services`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `service_synonyms` ADD CONSTRAINT `service_synonyms_serviceId_fkey` FOREIGN KEY (`serviceId`) REFERENCES `catalogue_services`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `dentist_service_prices` ADD CONSTRAINT `dentist_service_prices_dentistProfileId_fkey` FOREIGN KEY (`dentistProfileId`) REFERENCES `dentist_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `dentist_service_prices` ADD CONSTRAINT `dentist_service_prices_serviceId_fkey` FOREIGN KEY (`serviceId`) REFERENCES `catalogue_services`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `dentist_service_prices` ADD CONSTRAINT `dentist_service_prices_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `locations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `dentist_variant_prices` ADD CONSTRAINT `dentist_variant_prices_dentistServicePriceId_fkey` FOREIGN KEY (`dentistServicePriceId`) REFERENCES `dentist_service_prices`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `dentist_variant_prices` ADD CONSTRAINT `dentist_variant_prices_variantId_fkey` FOREIGN KEY (`variantId`) REFERENCES `service_variants`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `dentist_variant_prices` ADD CONSTRAINT `dentist_variant_prices_unitId_fkey` FOREIGN KEY (`unitId`) REFERENCES `price_units`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `dentist_packages` ADD CONSTRAINT `dentist_packages_dentistProfileId_fkey` FOREIGN KEY (`dentistProfileId`) REFERENCES `dentist_profiles`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `dentist_packages` ADD CONSTRAINT `dentist_packages_locationId_fkey` FOREIGN KEY (`locationId`) REFERENCES `locations`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `package_items` ADD CONSTRAINT `package_items_packageId_fkey` FOREIGN KEY (`packageId`) REFERENCES `dentist_packages`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `package_items` ADD CONSTRAINT `package_items_serviceId_fkey` FOREIGN KEY (`serviceId`) REFERENCES `catalogue_services`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `package_items` ADD CONSTRAINT `package_items_variantId_fkey` FOREIGN KEY (`variantId`) REFERENCES `service_variants`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `price_history` ADD CONSTRAINT `price_history_dentistServicePriceId_fkey` FOREIGN KEY (`dentistServicePriceId`) REFERENCES `dentist_service_prices`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `price_history` ADD CONSTRAINT `price_history_dentistVariantPriceId_fkey` FOREIGN KEY (`dentistVariantPriceId`) REFERENCES `dentist_variant_prices`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

