/**
 * TOOTHLOGY API REGISTRY
 *
 * Every HTTP endpoint is declared here before it exists as a route. The registry
 * is what makes the API surface reviewable as a whole rather than one file at a
 * time, and it enforces two things a code review reliably misses:
 *
 * 1. **`permissions: []` is a decision, not an omission.** An endpoint that is
 *    public says so explicitly with an empty array. There is no way to leave the
 *    field out, so "we forgot to add the permission check" cannot look identical
 *    to "this endpoint is intentionally public" (Constitution §9, default deny).
 * 2. **Mutations declare idempotency.** A non-idempotent POST that takes money or
 *    creates an appointment is a duplicate-charge incident waiting for a flaky
 *    network. The registry integrity test flags mutating endpoints that do not
 *    declare their idempotency stance.
 *
 * Only the three Phase 0 foundation endpoints exist as code. No domain endpoints
 * are registered — registering them would imply an API surface that does not
 * exist (Constitution P9).
 */

import type { ApiEndpoint } from './types';

/** The current API version. Breaking changes create v2; they never edit v1. */
export const CURRENT_API_VERSION = 'v1';

export const APIS: readonly ApiEndpoint[] = [
  {
    id: 'TL-API-HEALTH-001',
    name: 'Health check',
    description:
      'Liveness and readiness. Public callers get a bare ok/degraded status; dependency detail requires the health-read permission, because dependency topology is useful to an attacker.',
    status: 'implemented',
    phase: 1,
    method: 'GET',
    path: '/api/v1/health',
    version: 'v1',
    moduleId: 'TL-DEVOPS-HEALTH-001',
    permissions: [],
    authRequired: false,
    idempotent: true,
    rateLimit: 'public-generous',
    emits: [],
  },
  {
    id: 'TL-API-REGISTRY-001',
    name: 'Registry introspection',
    description:
      'Returns the architecture registry — divisions, modules, tools, permissions, flags and their statuses — so tooling and the admin console can read the live architecture rather than a stale document.',
    status: 'implemented',
    phase: 2,
    method: 'GET',
    path: '/api/v1/registry',
    version: 'v1',
    moduleId: 'TL-ADMIN-REGISTRY-001',
    permissions: ['tl.admin.registry.read'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-LOCALES-001',
    name: 'Supported locales',
    description:
      'Public reference data: enabled languages, their direction, and enabled countries with default currency and timezone. Lets any client bootstrap localization without hard-coding a list.',
    status: 'implemented',
    phase: 1,
    method: 'GET',
    path: '/api/v1/i18n/locales',
    version: 'v1',
    moduleId: 'TL-CORE-I18N-001',
    permissions: [],
    authRequired: false,
    idempotent: true,
    rateLimit: 'public-generous',
    emits: [],
  },
  // =========================================================================
  // PHASE 1 — Authentication (Division 01)
  // =========================================================================
  {
    id: 'TL-API-AUTH-REGISTER-001',
    name: 'Register',
    description:
      'Creates an account with a password credential, a self-assignable role, a profile and default notification preferences, then signs the user in and issues a verification token.',
    status: 'implemented',
    phase: 1,
    method: 'POST',
    path: '/api/v1/auth/register',
    version: 'v1',
    moduleId: 'TL-CORE-AUTH-001',
    permissions: [],
    authRequired: false,
    idempotent: true,
    rateLimit: 'auth-strict',
    emits: ['USER_CREATED'],
  },
  {
    id: 'TL-API-AUTH-LOGIN-001',
    name: 'Login',
    description:
      'Verifies a password and issues a session cookie. Responses are identical for every failure reason so the endpoint cannot be used to enumerate accounts.',
    status: 'implemented',
    phase: 1,
    method: 'POST',
    path: '/api/v1/auth/login',
    version: 'v1',
    moduleId: 'TL-CORE-AUTH-001',
    permissions: [],
    authRequired: false,
    idempotent: false,
    idempotencyExemption:
      'Each login mints a new session by definition; replaying one must create a second session, not return the first.',
    rateLimit: 'auth-strict',
    emits: [],
  },
  {
    id: 'TL-API-AUTH-LOGOUT-001',
    name: 'Logout',
    description:
      'Revokes the current session (or all of them) and clears the session cookie. Deliberately does not require authentication, so an expired session can still be cleared.',
    status: 'implemented',
    phase: 1,
    method: 'POST',
    path: '/api/v1/auth/logout',
    version: 'v1',
    moduleId: 'TL-CORE-AUTH-001',
    permissions: [],
    authRequired: false,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-AUTH-ME-001',
    name: 'Current user',
    description:
      'The caller’s own account, profiles, organization memberships and resolved permissions. The permission list is a UI affordance, never a security control.',
    status: 'implemented',
    phase: 1,
    method: 'GET',
    path: '/api/v1/auth/me',
    version: 'v1',
    moduleId: 'TL-CORE-AUTH-001',
    permissions: ['tl.core.user.read.self'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-AUTH-VERIFY-001',
    name: 'Verify contact',
    description:
      'Confirms an email address or phone number from a single-use token. Unauthenticated, because verification links are opened from an email client on any device.',
    status: 'implemented',
    phase: 1,
    method: 'POST',
    path: '/api/v1/auth/verify',
    version: 'v1',
    moduleId: 'TL-CORE-AUTH-001',
    permissions: [],
    authRequired: false,
    idempotent: true,
    rateLimit: 'auth-strict',
    emits: [],
  },
  {
    id: 'TL-API-AUTH-RESETREQ-001',
    name: 'Request password reset',
    description:
      'Issues a password reset token. Always responds identically whether or not the address is registered, so it cannot be used as a membership oracle.',
    status: 'implemented',
    phase: 1,
    method: 'POST',
    path: '/api/v1/auth/password/reset-request',
    version: 'v1',
    moduleId: 'TL-CORE-AUTH-001',
    permissions: [],
    authRequired: false,
    idempotent: true,
    rateLimit: 'costly',
    emits: [],
  },
  {
    id: 'TL-API-AUTH-RESET-001',
    name: 'Complete password reset',
    description:
      'Sets a new password from a reset token and revokes every existing session, so a compromised session cannot survive the reset that was meant to end it.',
    status: 'implemented',
    phase: 1,
    method: 'POST',
    path: '/api/v1/auth/password/reset',
    version: 'v1',
    moduleId: 'TL-CORE-AUTH-001',
    permissions: [],
    authRequired: false,
    idempotent: true,
    rateLimit: 'auth-strict',
    emits: [],
  },
  {
    id: 'TL-API-AUTH-CHANGEPW-001',
    name: 'Change password',
    description:
      'Changes the password of the signed-in user. Requires the current password, so an unattended logged-in device cannot become a permanent takeover.',
    status: 'implemented',
    phase: 1,
    method: 'POST',
    path: '/api/v1/auth/password/change',
    version: 'v1',
    moduleId: 'TL-CORE-AUTH-001',
    permissions: ['tl.core.user.update.self'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'auth-strict',
    emits: [],
  },
  {
    id: 'TL-API-AUTH-SESSIONS-001',
    name: 'List sessions',
    description:
      'The caller’s own active sessions with device and location detail, so an unrecognised session is visible and revocable.',
    status: 'implemented',
    phase: 1,
    method: 'GET',
    path: '/api/v1/auth/sessions',
    version: 'v1',
    moduleId: 'TL-CORE-AUTH-001',
    permissions: ['tl.core.session.read.self'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-AUTH-REVOKE-001',
    name: 'Revoke session',
    description:
      'Revokes one of the caller’s own sessions, or all others. Ownership is checked before revoking, so a supplied id belonging to another user is simply not found.',
    status: 'implemented',
    phase: 1,
    method: 'POST',
    path: '/api/v1/auth/sessions',
    version: 'v1',
    moduleId: 'TL-CORE-AUTH-001',
    permissions: ['tl.core.session.revoke.self'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  // =========================================================================
  // PHASE 1 — Organizations (Division 01)
  // =========================================================================
  {
    id: 'TL-API-ORG-CREATE-001',
    name: 'Create organization',
    description:
      'Creates an organization and makes the caller its administrator, in one transaction. Starts PENDING and is not publicly discoverable until verified.',
    status: 'implemented',
    phase: 1,
    method: 'POST',
    path: '/api/v1/organizations',
    version: 'v1',
    moduleId: 'TL-CORE-RBAC-001',
    permissions: [],
    authRequired: true,
    idempotent: false,
    idempotencyExemption:
      'Slug uniqueness makes a replay fail with CONFLICT rather than create a duplicate; there is no prior result to return.',
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-ORG-LIST-001',
    name: 'List my organizations',
    description:
      'Organizations the caller belongs to. There is deliberately no all-organizations listing here — that is an administrative capability.',
    status: 'implemented',
    phase: 1,
    method: 'GET',
    path: '/api/v1/organizations',
    version: 'v1',
    moduleId: 'TL-CORE-RBAC-001',
    permissions: [],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-ORG-GET-001',
    name: 'Get organization',
    description:
      'One organization with members and locations. Permission is evaluated against the organization in the route, so a member of a different clinic is denied.',
    status: 'implemented',
    phase: 1,
    method: 'GET',
    path: '/api/v1/organizations/:id',
    version: 'v1',
    moduleId: 'TL-CORE-RBAC-001',
    permissions: ['tl.core.organization.read'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-ORG-INVITE-001',
    name: 'Invite to organization',
    description:
      'Issues a single-use invitation token addressed to an email. Re-inviting revokes the previous invitation so only one is ever live per address.',
    status: 'implemented',
    phase: 1,
    method: 'POST',
    path: '/api/v1/organizations/:id/invitations',
    version: 'v1',
    moduleId: 'TL-CORE-RBAC-001',
    permissions: ['tl.core.organization.manage'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'costly',
    emits: [],
  },
  {
    id: 'TL-API-ORG-INVITELIST-001',
    name: 'List invitations',
    description:
      'Pending invitations for an organization. Requires only read, so staff can see who is pending without being able to add people.',
    status: 'implemented',
    phase: 1,
    method: 'GET',
    path: '/api/v1/organizations/:id/invitations',
    version: 'v1',
    moduleId: 'TL-CORE-RBAC-001',
    permissions: ['tl.core.organization.read'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-INVITE-ACCEPT-001',
    name: 'Accept invitation',
    description:
      'Joins an organization from an invitation token. The accepting account’s email must match the invited address, so a forwarded token cannot be redeemed by someone else.',
    status: 'implemented',
    phase: 1,
    method: 'POST',
    path: '/api/v1/invitations/accept',
    version: 'v1',
    moduleId: 'TL-CORE-RBAC-001',
    permissions: [],
    authRequired: true,
    idempotent: true,
    rateLimit: 'auth-strict',
    emits: [],
  },
  {
    id: 'TL-API-ORG-LOCCREATE-001',
    name: 'Create location',
    description:
      'Creates a branch with its address and opening hours in one transaction, and reports honestly whether it is discoverable.',
    status: 'implemented',
    phase: 1,
    method: 'POST',
    path: '/api/v1/organizations/:id/locations',
    version: 'v1',
    moduleId: 'TL-LOCATION-GEO-001',
    permissions: ['tl.core.organization.manage'],
    authRequired: true,
    idempotent: false,
    idempotencyExemption:
      'Slug uniqueness per organization makes a replay fail with CONFLICT rather than create a duplicate branch.',
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-ORG-LOCLIST-001',
    name: 'List locations',
    description: 'Branches for an organization, with addresses and opening hours.',
    status: 'implemented',
    phase: 1,
    method: 'GET',
    path: '/api/v1/organizations/:id/locations',
    version: 'v1',
    moduleId: 'TL-LOCATION-GEO-001',
    permissions: ['tl.core.organization.read'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  // =========================================================================
  // PHASE 3 — Dentists, clinics and verification (Divisions 04, 05, 26)
  // =========================================================================
  {
    id: 'TL-API-DENTIST-ME-GET-001',
    name: 'Get my dentist profile',
    description:
      'The caller’s own professional profile, including why they are or are not appearing in patient search.',
    status: 'implemented',
    phase: 3,
    method: 'GET',
    path: '/api/v1/dentists/me',
    version: 'v1',
    moduleId: 'TL-DENTIST-PROFILE-001',
    permissions: ['tl.dentist.profile.manage.self'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-DENTIST-ME-PUT-001',
    name: 'Save my dentist profile',
    description:
      'Creates or updates the caller’s professional profile and specialties. Cosmetic edits do not trigger re-verification; credential changes do.',
    status: 'implemented',
    phase: 3,
    method: 'PUT',
    path: '/api/v1/dentists/me',
    version: 'v1',
    moduleId: 'TL-DENTIST-PROFILE-001',
    permissions: ['tl.dentist.profile.manage.self'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-DENTIST-QUAL-001',
    name: 'Add qualification',
    description:
      'Adds a qualification. Doing so on a verified profile returns it to review, because the new credential has not been checked.',
    status: 'implemented',
    phase: 3,
    method: 'POST',
    path: '/api/v1/dentists/me/qualifications',
    version: 'v1',
    moduleId: 'TL-DENTIST-PROFILE-001',
    permissions: ['tl.dentist.profile.manage.self'],
    authRequired: true,
    idempotent: false,
    idempotencyExemption:
      'A dentist may legitimately hold two similar qualifications; deduplicating them automatically would discard a real credential.',
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-DENTIST-SUBMIT-001',
    name: 'Submit for verification',
    description:
      'Submits the profile for review. Completeness is checked first, and the error names exactly what is missing.',
    status: 'implemented',
    phase: 3,
    method: 'POST',
    path: '/api/v1/dentists/me/submit',
    version: 'v1',
    moduleId: 'TL-DENTIST-VERIFICATION-001',
    permissions: ['tl.dentist.profile.manage.self'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'costly',
    emits: [],
  },
  {
    id: 'TL-API-VERIFY-PENDING-001',
    name: 'Verification queue',
    description:
      'Requests awaiting review, oldest first so a backlog drains in the order it accumulated.',
    status: 'implemented',
    phase: 3,
    method: 'GET',
    path: '/api/v1/verification/pending',
    version: 'v1',
    moduleId: 'TL-DENTIST-VERIFICATION-001',
    permissions: ['tl.verification.request.review'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-VERIFY-REVIEW-001',
    name: 'Review a verification',
    description:
      'Approves or rejects a verification request. A reviewer may never decide their own application, and a rejection must carry a reason the applicant can act on.',
    status: 'implemented',
    phase: 3,
    method: 'POST',
    path: '/api/v1/verification/review',
    version: 'v1',
    moduleId: 'TL-DENTIST-VERIFICATION-001',
    permissions: ['tl.verification.request.review'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: ['DENTIST_VERIFIED'],
  },
  {
    id: 'TL-API-VERIFY-REVOKE-001',
    name: 'Revoke a verification',
    description:
      'Withdraws an approved verification and removes the subject from patient search immediately. Behind a separate permission from review.',
    status: 'implemented',
    phase: 3,
    method: 'POST',
    path: '/api/v1/verification/revoke',
    version: 'v1',
    moduleId: 'TL-DENTIST-VERIFICATION-001',
    permissions: ['tl.verification.request.revoke'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-DENTIST-PRACTICE-001',
    name: 'Claim a practice location',
    description:
      'A dentist claims they practise at a clinic location. The claim starts unconfirmed and confers nothing until the clinic confirms it.',
    status: 'implemented',
    phase: 3,
    method: 'POST',
    path: '/api/v1/dentists/me/practices',
    version: 'v1',
    moduleId: 'TL-DENTIST-PROFILE-001',
    permissions: ['tl.dentist.profile.manage.self'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-ORG-PRACTICELIST-001',
    name: 'List practice claims',
    description:
      'Dentists claiming to practise at this organization’s locations, unconfirmed first, with each one’s verification state.',
    status: 'implemented',
    phase: 3,
    method: 'GET',
    path: '/api/v1/organizations/:id/practices',
    version: 'v1',
    moduleId: 'TL-DENTIST-PROFILE-001',
    permissions: ['tl.core.organization.read'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-ORG-PRACTICECONFIRM-001',
    name: 'Confirm a practice claim',
    description:
      'The clinic confirms a dentist practises at one of its locations. Without this, any dentist could appear in any clinic’s results.',
    status: 'implemented',
    phase: 3,
    method: 'POST',
    path: '/api/v1/organizations/:id/practices',
    version: 'v1',
    moduleId: 'TL-DENTIST-PROFILE-001',
    permissions: ['tl.clinic.practice.confirm'],
    authRequired: true,
    idempotent: true,
    rateLimit: 'authenticated-standard',
    emits: [],
  },
  {
    id: 'TL-API-SPECIALTIES-001',
    name: 'List dental specialties',
    description:
      'Public specialty reference data with patient-facing descriptions, powering the profile editor and discovery filters.',
    status: 'implemented',
    phase: 3,
    method: 'GET',
    path: '/api/v1/specialties',
    version: 'v1',
    moduleId: 'TL-DENTIST-PROFILE-001',
    permissions: [],
    authRequired: false,
    idempotent: true,
    rateLimit: 'public-generous',
    emits: [],
  },
] as const;

export const API_BY_ID: ReadonlyMap<string, ApiEndpoint> = new Map(APIS.map((a) => [a.id, a]));

/** Endpoints that change state. Used by the integrity test's idempotency check. */
export const MUTATING_METHODS = new Set(['POST', 'PUT', 'PATCH', 'DELETE']);
