/**
 * TOOTHLOGY EVENT & NOTIFICATION REGISTRY
 *
 * Domain events are the seam between divisions. A division announces that
 * something happened in its own data; other divisions react without the
 * publisher knowing they exist. This is what keeps 35 divisions from turning
 * into 35 × 34 direct dependencies.
 *
 * Rules that make events safe rather than merely convenient:
 *
 * 1. **Events are facts, in the past tense.** `APPOINTMENT_CONFIRMED`, never
 *    `CONFIRM_APPOINTMENT`. An event is not a command and a subscriber may not
 *    be assumed to exist.
 * 2. **Payloads carry IDs, not sensitive bodies.** `payloadSensitivity` records
 *    the highest classification a payload may contain; a `phi` payload may never
 *    be logged or shipped to an external analytics provider. Single-use secrets
 *    (reset links, one-time codes) are NEVER written to the outbox at all —
 *    those notifications are sent directly, so a database read cannot yield a
 *    working reset link.
 * 3. **Every event name is registered here before it is published.** The event
 *    bus and the outbox writer both reject unregistered names.
 *
 * STATUS: `implemented` means a publisher AND at least one durable handler
 * exist and are tested. `prepared` means the contract is reserved for a later
 * phase with no publisher yet (Constitution P9).
 */

import type { EventDefinition, NotificationDefinition } from './types';

export const EVENTS: readonly EventDefinition[] = [
  // --- Phase 1: identity -----------------------------------------------------
  {
    id: 'TL-EVT-USER-CREATED-001',
    event: 'USER_CREATED',
    name: 'User created',
    description: 'A new user account was created and is ready for onboarding.',
    status: 'implemented',
    phase: 1,
    divisionId: 'TL-DIV-01-CORE',
    payloadSensitivity: 'internal',
    notifies: ['TL-NOTIF-WELCOME-001'],
  },
  {
    id: 'TL-EVT-SECURITY-ALERT-001',
    event: 'SECURITY_ALERT_RAISED',
    name: 'Security alert raised',
    description:
      'A security-relevant change or signal on an account: a sign-in from a new device, MFA turned off, recovery codes used. The account owner is told on every channel they have.',
    status: 'implemented',
    phase: 1,
    divisionId: 'TL-DIV-33-SECURITY',
    payloadSensitivity: 'internal',
    notifies: ['TL-NOTIF-SECURITY-ALERT-001'],
  },
  {
    id: 'TL-EVT-ORG-MEMBER-JOINED-001',
    event: 'ORGANIZATION_MEMBER_JOINED',
    name: 'Organization member joined',
    description: 'An invitation was accepted. The organization’s administrators are told who joined.',
    status: 'implemented',
    phase: 1,
    divisionId: 'TL-DIV-01-CORE',
    payloadSensitivity: 'internal',
    notifies: ['TL-NOTIF-ORG-MEMBER-JOINED-001'],
  },

  // --- Phase 3: trust ----------------------------------------------------------
  {
    id: 'TL-EVT-DENTIST-VERIFIED-001',
    event: 'DENTIST_VERIFIED',
    name: 'Dentist verification decided',
    description:
      'A dentist’s verification was approved, rejected or revoked. Revocation is its own decision on the same request, never a deletion of the approval (Constitution P2).',
    status: 'implemented',
    phase: 3,
    divisionId: 'TL-DIV-04-DENTISTS',
    payloadSensitivity: 'confidential',
    notifies: ['TL-NOTIF-VERIFICATION-RESULT-001'],
  },
  {
    id: 'TL-EVT-CLINIC-VERIFIED-001',
    event: 'CLINIC_VERIFIED',
    name: 'Organization verification decided',
    description: 'A clinic, hospital, college or supplier verification was approved, rejected or revoked.',
    status: 'implemented',
    phase: 3,
    divisionId: 'TL-DIV-05-CLINICS',
    payloadSensitivity: 'confidential',
    notifies: ['TL-NOTIF-VERIFICATION-RESULT-001'],
  },
  {
    id: 'TL-EVT-PRACTICE-CLAIMED-001',
    event: 'PRACTICE_CLAIMED',
    name: 'Practice claimed',
    description: 'A dentist claimed to practise at a location. The clinic must confirm before anything is public.',
    status: 'implemented',
    phase: 3,
    divisionId: 'TL-DIV-05-CLINICS',
    payloadSensitivity: 'internal',
    notifies: ['TL-NOTIF-PRACTICE-CLAIM-001'],
  },
  {
    id: 'TL-EVT-PRACTICE-CONFIRMED-001',
    event: 'PRACTICE_CONFIRMED',
    name: 'Practice confirmed',
    description: 'A clinic confirmed a dentist practises at one of its locations.',
    status: 'implemented',
    phase: 3,
    divisionId: 'TL-DIV-05-CLINICS',
    payloadSensitivity: 'internal',
    notifies: ['TL-NOTIF-PRACTICE-CONFIRMED-001'],
  },

  // --- Phase 4: appointments -------------------------------------------------
  {
    id: 'TL-EVT-APPOINTMENT-CREATED-001',
    event: 'APPOINTMENT_CREATED',
    name: 'Appointment created',
    description:
      'A patient booked (instant booking) or requested (request booking) an appointment. The payload records which, because the practice must act on a request.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    payloadSensitivity: 'confidential',
    notifies: ['TL-NOTIF-APPOINTMENT-CREATED-001', 'TL-NOTIF-APPOINTMENT-REQUESTED-001', 'TL-NOTIF-APPOINTMENT-CONFIRMED-001'],
  },
  {
    id: 'TL-EVT-APPOINTMENT-CHECKEDIN-001',
    event: 'APPOINTMENT_CHECKED_IN',
    name: 'Patient checked in',
    description: 'The patient arrived and was checked in, by themselves or by the practice. The other side is told.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    payloadSensitivity: 'confidential',
    notifies: ['TL-NOTIF-APPOINTMENT-CHECKED-IN-001'],
  },
  {
    id: 'TL-EVT-APPOINTMENT-CONFIRMED-001',
    event: 'APPOINTMENT_CONFIRMED',
    name: 'Appointment confirmed',
    description:
      'The practice confirmed the appointment. This is the moment the BOOK pillar promise becomes binding.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    payloadSensitivity: 'confidential',
    notifies: ['TL-NOTIF-APPOINTMENT-CONFIRMED-001'],
  },
  {
    id: 'TL-EVT-APPOINTMENT-REJECTED-001',
    event: 'APPOINTMENT_REJECTED',
    name: 'Appointment request declined',
    description: 'The practice declined a request. The patient is offered alternatives, never a dead end.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    payloadSensitivity: 'confidential',
    notifies: ['TL-NOTIF-APPOINTMENT-REJECTED-001'],
  },
  {
    id: 'TL-EVT-APPOINTMENT-CANCELLED-001',
    event: 'APPOINTMENT_CANCELLED',
    name: 'Appointment cancelled',
    description:
      'The appointment was cancelled. The payload records who cancelled it, because refund and no-show rules depend on that.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    payloadSensitivity: 'confidential',
    notifies: ['TL-NOTIF-APPOINTMENT-CANCELLED-001'],
  },
  {
    id: 'TL-EVT-APPOINTMENT-RESCHEDULED-001',
    event: 'APPOINTMENT_RESCHEDULED',
    name: 'Appointment rescheduled',
    description: 'An appointment moved to a new time. Both sides are told the old and new times.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    payloadSensitivity: 'confidential',
    notifies: ['TL-NOTIF-APPOINTMENT-RESCHEDULED-001'],
  },
  {
    id: 'TL-EVT-APPOINTMENT-COMPLETED-001',
    event: 'APPOINTMENT_COMPLETED',
    name: 'Appointment completed',
    description:
      'The visit took place. Settles the lead and carries the follow-up recommendation, where the dentist set one. (Reviews are Phase 5.)',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    payloadSensitivity: 'confidential',
    notifies: ['TL-NOTIF-APPOINTMENT-COMPLETED-001'],
  },
  {
    id: 'TL-EVT-APPOINTMENT-NOSHOW-001',
    event: 'APPOINTMENT_NO_SHOW',
    name: 'Appointment no-show',
    description: 'The patient did not attend. Recorded by the practice after the start time.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    payloadSensitivity: 'confidential',
    notifies: [],
  },
  {
    id: 'TL-EVT-APPOINTMENT-EXPIRED-001',
    event: 'APPOINTMENT_EXPIRED',
    name: 'Appointment request expired',
    description: 'A request the practice never answered lapsed. The patient is released to book elsewhere.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    payloadSensitivity: 'confidential',
    notifies: ['TL-NOTIF-APPOINTMENT-REJECTED-001'],
  },
  {
    id: 'TL-EVT-WAITLIST-OFFER-001',
    event: 'WAITLIST_SLOT_OFFERED',
    name: 'Waitlist slot offered',
    description: 'A cancellation freed a slot matching a waitlist entry.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    payloadSensitivity: 'internal',
    notifies: ['TL-NOTIF-WAITLIST-OFFER-001'],
  },

  // --- Phase 4: leads and billing -------------------------------------------
  {
    id: 'TL-EVT-LEAD-CREATED-001',
    event: 'LEAD_CREATED',
    name: 'Lead created',
    description: 'A qualified callback lead was paid for and delivered to the practice, which is now told. (Booking leads reach the practice through the appointment itself.)',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-20-LEADS',
    payloadSensitivity: 'confidential',
    notifies: ['TL-NOTIF-LEAD-OFFER-001'],
  },
  {
    id: 'TL-EVT-LEAD-ACCEPTED-001',
    event: 'LEAD_ACCEPTED',
    name: 'Lead accepted',
    description: 'A practice accepted a callback lead; the patient is told the practice will contact them. The qualified-lead charge is taken at qualification, not here.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-20-LEADS',
    payloadSensitivity: 'confidential',
    notifies: ['TL-NOTIF-LEAD-ACCEPTED-001'],
  },
  {
    id: 'TL-EVT-LEAD-REFUNDED-001',
    event: 'LEAD_REFUNDED',
    name: 'Lead refunded',
    description: 'A disputed or invalid lead was refunded to the practice wallet.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-20-LEADS',
    payloadSensitivity: 'internal',
    notifies: ['TL-NOTIF-BILLING-UPDATE-001'],
  },
  {
    id: 'TL-EVT-WALLET-CREDITED-001',
    event: 'WALLET_CREDITED',
    name: 'Wallet credited',
    description: 'Credit was added to a practice wallet — a confirmed payment, or a recorded offline transfer.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-23-PAYMENTS',
    payloadSensitivity: 'internal',
    notifies: ['TL-NOTIF-BILLING-UPDATE-001'],
  },
  {
    id: 'TL-EVT-LEAD-BILLED-001',
    event: 'LEAD_BILLED',
    name: 'Lead billed',
    description: 'The billing decision on a qualified lead: FREE (inside the free allowance), CHARGED (a wallet debit, price plus GST) or PENDING_FUNDS.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-20-LEADS',
    payloadSensitivity: 'internal',
    notifies: ['TL-NOTIF-LEAD-BILLED-001'],
  },
  {
    id: 'TL-EVT-WALLET-LOW-001',
    event: 'WALLET_LOW_BALANCE',
    name: 'Wallet low',
    description: 'A charge took the wallet below the configured number of paid leads. Emitted on crossing the line, not on every charge below it.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-23-PAYMENTS',
    payloadSensitivity: 'internal',
    notifies: ['TL-NOTIF-WALLET-LOW-BALANCE-001'],
  },
  {
    id: 'TL-EVT-CAMPAIGN-ACTIVATED-001',
    event: 'SPONSORED_CAMPAIGN_ACTIVATED',
    name: 'Sponsored campaign activated',
    description: 'A Prime campaign was activated and its budget held from the wallet.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-22-ADVERTISING',
    payloadSensitivity: 'internal',
    notifies: ['TL-NOTIF-CAMPAIGN-UPDATE-001'],
  },
  {
    id: 'TL-EVT-CAMPAIGN-CLOSED-001',
    event: 'SPONSORED_CAMPAIGN_CLOSED',
    name: 'Sponsored campaign closed',
    description: 'A Prime campaign ended, spent its budget or was cancelled; any unspent budget was refunded to the wallet.',
    status: 'implemented',
    phase: 4,
    divisionId: 'TL-DIV-22-ADVERTISING',
    payloadSensitivity: 'internal',
    notifies: ['TL-NOTIF-CAMPAIGN-UPDATE-001'],
  },
  {
    id: 'TL-EVT-PAYMENT-COMPLETED-001',
    event: 'PAYMENT_COMPLETED',
    name: 'Payment completed',
    description:
      'A payment was captured and confirmed by the provider. Emitted only on provider confirmation — never optimistically (Constitution P10).',
    status: 'prepared',
    phase: 4,
    divisionId: 'TL-DIV-23-PAYMENTS',
    payloadSensitivity: 'confidential',
    notifies: ['TL-NOTIF-PAYMENT-RECEIPT-001'],
  },

  // --- Later phases (contracts reserved) -------------------------------------
  {
    id: 'TL-EVT-REVIEW-CREATED-001',
    event: 'REVIEW_CREATED',
    name: 'Review created',
    description: 'A patient reviewed a completed visit. It is published at once; a moderator acts only on a flag. The payload carries ids and the rating, never the text.',
    status: 'implemented',
    phase: 5,
    divisionId: 'TL-DIV-26-REVIEWS',
    payloadSensitivity: 'internal',
    notifies: ['TL-NOTIF-REVIEW-RECEIVED-001'],
  },
  {
    id: 'TL-EVT-MESSAGE-RECEIVED-001',
    event: 'MESSAGE_RECEIVED',
    name: 'Message received',
    description:
      'A message arrived in a thread. The payload carries thread and sender IDs only — never message content.',
    status: 'implemented',
    phase: 5,
    divisionId: 'TL-DIV-25-COMMUNICATION',
    payloadSensitivity: 'confidential',
    notifies: ['TL-NOTIF-NEW-MESSAGE-001'],
  },
  {
    id: 'TL-EVT-ORDER-CREATED-001',
    event: 'ORDER_CREATED',
    name: 'Order created',
    description: 'A marketplace order was placed. The payload carries the order and seller IDs only.',
    status: 'implemented',
    phase: 9,
    divisionId: 'TL-DIV-16-MARKETPLACE',
    payloadSensitivity: 'confidential',
    notifies: ['TL-NOTIF-ORDER-CONFIRMATION-001'],
  },
  {
    id: 'TL-EVT-DEVICE-CONNECTED-001',
    event: 'DEVICE_CONNECTED',
    name: 'Device connected',
    description: 'An IoT dental device paired with a clinic and began reporting telemetry.',
    status: 'implemented',
    phase: 11,
    divisionId: 'TL-DIV-28-IOT',
    payloadSensitivity: 'internal',
    notifies: [],
  },
] as const;

export const EVENT_BY_NAME: ReadonlyMap<string, EventDefinition> = new Map(
  EVENTS.map((e) => [e.event, e]),
);

export const EVENT_NAMES = EVENTS.map((e) => e.event);

export function isKnownEvent(name: string): boolean {
  return EVENT_BY_NAME.has(name);
}

// ---------------------------------------------------------------------------
// Notifications
// ---------------------------------------------------------------------------

/**
 * `transactional: true` means the notification is part of a service the user
 * asked for — a booking confirmation, a payment receipt — and is delivered even
 * if the user has opted out of marketing. `transactional: false` must respect
 * marketing consent in every channel and in every jurisdiction.
 *
 * Getting this boolean wrong is a compliance incident, not a UX bug, which is
 * why it is a required field rather than an inferred default.
 */
export const NOTIFICATIONS: readonly NotificationDefinition[] = [
  // --- Account & security ----------------------------------------------------
  {
    id: 'TL-NOTIF-WELCOME-001',
    name: 'Welcome',
    description: 'Onboarding message sent after account creation.',
    status: 'implemented',
    phase: 1,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-01-CORE',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-EMAIL-VERIFY-001',
    name: 'Verify your email',
    description:
      'A single-use verification link. Sent directly, never through the outbox, so the link never rests in the database.',
    status: 'implemented',
    phase: 1,
    channels: ['email'],
    transactional: true,
    divisionId: 'TL-DIV-01-CORE',
    category: 'account',
    urgent: true,
  },
  {
    id: 'TL-NOTIF-PHONE-OTP-001',
    name: 'Phone verification code',
    description: 'A one-time code to confirm a phone number. Sent directly; the code is never stored in plaintext.',
    status: 'implemented',
    phase: 1,
    channels: ['sms'],
    transactional: true,
    divisionId: 'TL-DIV-01-CORE',
    category: 'account',
    urgent: true,
  },
  {
    id: 'TL-NOTIF-PASSWORD-RESET-001',
    name: 'Password reset',
    description: 'A single-use password reset link. Sent directly, never through the outbox.',
    status: 'implemented',
    phase: 1,
    channels: ['email'],
    transactional: true,
    divisionId: 'TL-DIV-01-CORE',
    category: 'security',
    urgent: true,
  },
  {
    id: 'TL-NOTIF-SECURITY-ALERT-001',
    name: 'Security alert',
    description: 'Something security-relevant happened on the account: a new device, MFA changes, a password change.',
    status: 'implemented',
    phase: 1,
    channels: ['in_app', 'email', 'sms'],
    transactional: true,
    divisionId: 'TL-DIV-33-SECURITY',
    category: 'security',
    urgent: true,
  },
  {
    id: 'TL-NOTIF-ORG-INVITATION-001',
    name: 'Organization invitation',
    description: 'An invitation to join an organization, with a single-use acceptance link. Sent directly.',
    status: 'implemented',
    phase: 1,
    channels: ['email'],
    transactional: true,
    divisionId: 'TL-DIV-01-CORE',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-ORG-MEMBER-JOINED-001',
    name: 'Member joined',
    description: 'Tells organization administrators that an invitation was accepted.',
    status: 'implemented',
    phase: 1,
    channels: ['in_app'],
    transactional: true,
    divisionId: 'TL-DIV-01-CORE',
    category: 'account',
  },

  // --- Trust -------------------------------------------------------------------
  {
    id: 'TL-NOTIF-VERIFICATION-RESULT-001',
    name: 'Verification result',
    description: 'Informs a dentist or clinic that verification succeeded, failed or was revoked.',
    status: 'implemented',
    phase: 3,
    channels: ['in_app', 'email', 'sms'],
    transactional: true,
    divisionId: 'TL-DIV-26-REVIEWS',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-PRACTICE-CLAIM-001',
    name: 'Practice claim received',
    description: 'Tells clinic administrators a dentist has claimed to practise at one of their locations.',
    status: 'implemented',
    phase: 3,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-05-CLINICS',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-PRACTICE-CONFIRMED-001',
    name: 'Practice confirmed',
    description: 'Tells a dentist the clinic confirmed their practice claim.',
    status: 'implemented',
    phase: 3,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-05-CLINICS',
    category: 'account',
  },

  // --- Appointments ------------------------------------------------------------
  {
    id: 'TL-NOTIF-APPOINTMENT-CREATED-001',
    name: 'New appointment',
    description: 'Tells the practice a new booking was made, or a request needs a decision.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'push', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    category: 'appointments',
  },
  {
    id: 'TL-NOTIF-APPOINTMENT-REQUESTED-001',
    name: 'Request sent',
    description: 'Tells the patient their request was sent and when the practice must answer — never that it is confirmed.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    category: 'appointments',
  },
  {
    id: 'TL-NOTIF-APPOINTMENT-CHECKED-IN-001',
    name: 'Checked in',
    description: 'Tells the practice a patient has arrived, or the patient that the practice checked them in.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app'],
    transactional: true,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    category: 'appointments',
  },
  {
    id: 'TL-NOTIF-APPOINTMENT-CONFIRMED-001',
    name: 'Appointment confirmed',
    description: 'Confirms the booking to the patient with time, place and preparation notes.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'push', 'email', 'sms', 'whatsapp'],
    transactional: true,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    category: 'appointments',
  },
  {
    id: 'TL-NOTIF-APPOINTMENT-REJECTED-001',
    name: 'Appointment request declined',
    description: 'Tells the patient a request was declined or lapsed, with a route to other available slots.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'email', 'sms'],
    transactional: true,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    category: 'appointments',
    urgent: true,
  },
  {
    id: 'TL-NOTIF-APPOINTMENT-CANCELLED-001',
    name: 'Appointment cancelled',
    description: 'Notifies both sides of a cancellation and any refund consequence.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'push', 'email', 'sms'],
    transactional: true,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    category: 'appointments',
    urgent: true,
  },
  {
    id: 'TL-NOTIF-APPOINTMENT-RESCHEDULED-001',
    name: 'Appointment rescheduled',
    description: 'Tells both sides an appointment moved, with the old and the new time.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'push', 'email', 'sms'],
    transactional: true,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    category: 'appointments',
    urgent: true,
  },
  {
    id: 'TL-NOTIF-APPOINTMENT-REMINDER-001',
    name: 'Appointment tomorrow',
    description:
      'The day-before reminder: sent within 24 hours of the start, when the appointment is on a later local date (the branch’s timezone). Once per appointment time.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'push', 'sms', 'whatsapp'],
    transactional: true,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    category: 'appointments',
  },
  {
    id: 'TL-NOTIF-APPOINTMENT-TODAY-001',
    name: 'Appointment today',
    description: 'Sent from 07:00 local on the appointment day, when it is more than two hours away. Once per appointment time.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'push', 'sms'],
    transactional: true,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    category: 'appointments',
  },
  {
    id: 'TL-NOTIF-APPOINTMENT-SOON-001',
    name: 'Appointment soon',
    description: 'Sent within two hours of the start, with the check-in route. Once per appointment time.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'push', 'sms'],
    transactional: true,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    category: 'appointments',
    urgent: true,
  },
  {
    id: 'TL-NOTIF-APPOINTMENT-COMPLETED-001',
    name: 'Visit completed',
    description: 'Thanks the patient and carries any follow-up recommendation. It does not invite a review: reviews are Phase 5 and not built.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    category: 'appointments',
  },
  {
    id: 'TL-NOTIF-FOLLOW-UP-DUE-001',
    name: 'Follow-up due',
    description: 'The follow-up the dentist recommended is due; rebooking is one tap.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'email', 'sms'],
    transactional: true,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    category: 'appointments',
  },
  {
    id: 'TL-NOTIF-WAITLIST-OFFER-001',
    name: 'A slot opened up',
    description: 'A slot on the patient’s waitlist became free. First to book gets it.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'push', 'sms'],
    transactional: true,
    divisionId: 'TL-DIV-09-APPOINTMENTS',
    category: 'appointments',
    urgent: true,
  },

  // --- Leads & billing ---------------------------------------------------------
  {
    id: 'TL-NOTIF-LEAD-OFFER-001',
    name: 'New patient lead',
    description: 'Offers a new qualified patient lead to a practice.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'push', 'email', 'sms'],
    transactional: true,
    divisionId: 'TL-DIV-20-LEADS',
    category: 'leads',
  },
  {
    id: 'TL-NOTIF-LEAD-ACCEPTED-001',
    name: 'Your request was accepted',
    description: 'Tells the patient the practice accepted their request and will contact them.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'email', 'sms'],
    transactional: true,
    divisionId: 'TL-DIV-20-LEADS',
    category: 'appointments',
  },
  {
    id: 'TL-NOTIF-BILLING-UPDATE-001',
    name: 'Billing update',
    description: 'A wallet recharge or credit, or a refund to the wallet.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-23-PAYMENTS',
    category: 'billing',
  },
  {
    id: 'TL-NOTIF-LEAD-BILLED-001',
    name: 'Lead billing',
    description: 'A qualified lead was free, was charged to the wallet (price plus GST), or is waiting for funds.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-20-LEADS',
    category: 'billing',
  },
  {
    id: 'TL-NOTIF-WALLET-LOW-BALANCE-001',
    name: 'Wallet running low',
    description: 'The wallet now covers fewer paid leads than the configured warning level.',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-23-PAYMENTS',
    category: 'billing',
  },
  {
    id: 'TL-NOTIF-CAMPAIGN-UPDATE-001',
    name: 'Prime campaign update',
    description: 'A sponsored campaign started (budget held) or closed (with what was spent and refunded).',
    status: 'implemented',
    phase: 4,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-22-ADVERTISING',
    category: 'billing',
  },
  ...(
    [
      ['TL-NOTIF-CAMP-REVIEW-001', 'Camp reviewed', 'Tells an organizer their camp was approved (now public) or not, with the reason.'],
      ['TL-NOTIF-CAMP-APPLICATION-001', 'Doctor applied to your camp', 'Tells an organizer a verified dentist applied to serve at their camp.'],
      ['TL-NOTIF-CAMP-PARTICIPATION-001', 'Your camp participation', 'Tells a dentist their application was approved or declined, or that the camp was cancelled.'],
      ['TL-NOTIF-CAMP-UPDATE-001', 'Your camp', 'Tells a patient they are registered, that a camp doctor can see them for follow-up, or that the camp was cancelled.'],
    ] as const
  ).map(([id, name, description]) => ({
    id,
    name,
    description,
    status: 'implemented' as const,
    phase: 5 as const,
    channels: ['in_app'] as const,
    transactional: true,
    divisionId: 'TL-DIV-04-DENTISTS',
    category: 'appointments' as const,
  })),
  {
    id: 'TL-NOTIF-FACULTY-REQUEST-001',
    name: 'Faculty post to confirm',
    description: 'Tells a college’s administrators someone asked them to confirm a faculty post.',
    status: 'implemented',
    phase: 8,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-06-COLLEGES',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-FACULTY-DECISION-001',
    name: 'Your faculty post',
    description: 'Tells a faculty member the college confirmed, declined or ended their post.',
    status: 'implemented',
    phase: 8,
    channels: ['in_app'],
    transactional: true,
    divisionId: 'TL-DIV-06-COLLEGES',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-COMMUNITY-ANSWER-001',
    name: 'New answer to your question',
    description: 'Tells someone their community question has a new answer.',
    status: 'implemented',
    phase: 7,
    channels: ['in_app'],
    transactional: true,
    divisionId: 'TL-DIV-15-MEDIA',
    category: 'messages',
  },
  {
    id: 'TL-NOTIF-COMMUNITY-MODERATION-001',
    name: 'Your post was hidden',
    description: 'Tells an author their community post was hidden — after several reports, or by a moderator with the reason.',
    status: 'implemented',
    phase: 7,
    channels: ['in_app'],
    transactional: true,
    divisionId: 'TL-DIV-15-MEDIA',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-QUOTE-REQUEST-001',
    name: 'Quote request',
    description: 'Tells a business’s administrators about a new quote request, or that their quote was accepted. Names the product and quantity, not the buyer.',
    status: 'implemented',
    phase: 9,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-16-MARKETPLACE',
    category: 'leads',
  },
  {
    id: 'TL-NOTIF-QUOTE-UPDATE-001',
    name: 'Your quote request',
    description: 'Tells a buyer a seller quoted or declined.',
    status: 'implemented',
    phase: 9,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-16-MARKETPLACE',
    category: 'marketplace',
  },
  {
    id: 'TL-NOTIF-ADMISSION-ENQUIRY-001',
    name: 'New admission enquiry',
    description: 'Tells a college’s administrators a student enquired about a course. Names the course, not the student.',
    status: 'implemented',
    phase: 8,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-06-COLLEGES',
    category: 'leads',
  },
  {
    id: 'TL-NOTIF-ADMISSION-UPDATE-001',
    name: 'Your admission enquiry',
    description: 'Tells a student their enquiry was marked contacted, applied, admitted, not admitted or closed.',
    status: 'implemented',
    phase: 8,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-07-STUDENTS',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-LEAD-FOLLOW-UP-001',
    name: 'Lead follow-up due',
    description: 'Tells whoever is working a lead (or the practice’s administrators, if nobody is) that its follow-up call is due. Carries no patient details.',
    status: 'implemented',
    phase: 5,
    channels: ['in_app'],
    transactional: true,
    divisionId: 'TL-DIV-20-LEADS',
    category: 'leads',
  },
  {
    id: 'TL-NOTIF-LEAD-ASSIGNED-001',
    name: 'Lead assigned to you',
    description: 'Tells a practice member a lead was assigned to them. Carries no patient details.',
    status: 'implemented',
    phase: 5,
    channels: ['in_app'],
    transactional: true,
    divisionId: 'TL-DIV-20-LEADS',
    category: 'leads',
  },
  {
    id: 'TL-NOTIF-ACCOUNT-ACTIVATION-001',
    name: 'Activate your profile',
    description: 'The email half of activating a pre-made profile: a single-use link, used together with a code sent to the mobile.',
    status: 'implemented',
    phase: 5,
    channels: ['email'],
    transactional: true,
    divisionId: 'TL-DIV-03-USERS',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-PAYMENT-RECEIPT-001',
    name: 'Payment receipt',
    description: 'Receipt issued after a confirmed capture, with tax breakdown.',
    status: 'prepared',
    phase: 4,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-23-PAYMENTS',
    category: 'billing',
  },

  // --- Later phases --------------------------------------------------------------
  {
    id: 'TL-NOTIF-REVIEW-RECEIVED-001',
    name: 'Review received',
    description: 'Tells a practice a review was published and may be responded to.',
    status: 'implemented',
    phase: 5,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-26-REVIEWS',
    category: 'reviews',
  },
  {
    id: 'TL-NOTIF-REVIEW-RESPONSE-001',
    name: 'Reply to your review',
    description: 'Tells a patient the practice replied to their review.',
    status: 'implemented',
    phase: 5,
    channels: ['in_app'],
    transactional: true,
    divisionId: 'TL-DIV-26-REVIEWS',
    category: 'reviews',
  },
  {
    id: 'TL-NOTIF-REVIEW-MODERATION-001',
    name: 'Your review was hidden',
    description: 'Tells a patient a moderator hid their review, with the reason.',
    status: 'implemented',
    phase: 5,
    channels: ['in_app'],
    transactional: true,
    divisionId: 'TL-DIV-26-REVIEWS',
    category: 'reviews',
  },
  {
    id: 'TL-NOTIF-SUPPORT-UPDATE-001',
    name: 'Your support request',
    description: 'Tells someone Toothlogy support replied to their ticket or resolved it. Internal notes never notify.',
    status: 'implemented',
    phase: 5,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-30-SUPPORT',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-RECORD-ACCESS-REQUEST-001',
    name: 'A practice asks to see your dental record',
    description: 'Tells a patient a practice asked for access to their dental record; nothing is shared until they allow it.',
    status: 'implemented',
    phase: 6,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-11-RECORDS',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-RECORD-ACCESS-DECISION-001',
    name: 'Dental record access decided',
    description: 'Tells a practice’s administrators a patient shared, declined or withdrew access to their dental record.',
    status: 'implemented',
    phase: 6,
    channels: ['in_app'],
    transactional: true,
    divisionId: 'TL-DIV-11-RECORDS',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-RECORD-UPDATED-001',
    name: 'Your dental record changed',
    description: 'Tells a patient a practice added to their record, proposed or changed a treatment plan, or cancelled a prescription — who, never the clinical detail.',
    status: 'implemented',
    phase: 6,
    channels: ['in_app'],
    transactional: true,
    divisionId: 'TL-DIV-11-RECORDS',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-TREATMENT-PLAN-001',
    name: 'Treatment plan decided',
    description: 'Tells a practice’s administrators a patient accepted or declined a treatment plan it proposed — who, never the clinical detail.',
    status: 'implemented',
    phase: 6,
    channels: ['in_app'],
    transactional: true,
    divisionId: 'TL-DIV-11-RECORDS',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-PRESCRIPTION-ISSUED-001',
    name: 'New prescription',
    description: 'Tells a patient a practice issued them a prescription, without its contents.',
    status: 'implemented',
    phase: 6,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-12-PRESCRIPTIONS',
    category: 'appointments',
  },
  {
    id: 'TL-NOTIF-ENROLMENT-001',
    name: 'Your enrolment',
    description: 'Tells a student a college enrolled them, or marked their enrolment completed or withdrawn.',
    status: 'implemented',
    phase: 8,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-07-STUDENTS',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-DEVICE-ALERT-001',
    name: 'Equipment alert',
    description: 'Tells a practice’s administrators a connected device reported a reading outside its limits, or a fault.',
    status: 'implemented',
    phase: 11,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-28-IOT',
    category: 'account',
  },
  {
    id: 'TL-NOTIF-APPLICATION-RECEIVED-001',
    name: 'New job application',
    description: 'Tells an employer’s administrators someone applied for one of their postings.',
    status: 'implemented',
    phase: 8,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-08-CAREERS',
    category: 'careers',
  },
  {
    id: 'TL-NOTIF-APPLICATION-UPDATE-001',
    name: 'Your application moved on',
    description: 'Tells an applicant they were shortlisted, invited to interview, offered, hired or not taken forward.',
    status: 'implemented',
    phase: 8,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-08-CAREERS',
    category: 'careers',
  },
  {
    id: 'TL-NOTIF-ARTICLE-REVIEWED-001',
    name: 'Your article was reviewed',
    description: 'Tells an author their article was published, needs changes, or was taken off Toothlogy.',
    status: 'implemented',
    phase: 7,
    channels: ['in_app'],
    transactional: true,
    divisionId: 'TL-DIV-13-KNOWLEDGE',
    category: 'community',
  },
  {
    id: 'TL-NOTIF-NEW-MESSAGE-001',
    name: 'New message',
    description: 'Alerts a participant to a new message without including its content.',
    status: 'implemented',
    phase: 5,
    channels: ['in_app', 'push'],
    transactional: true,
    divisionId: 'TL-DIV-25-COMMUNICATION',
    category: 'messages',
  },
  {
    id: 'TL-NOTIF-ORDER-CONFIRMATION-001',
    name: 'Order confirmation',
    description: 'Tells a buyer their order was placed, with its number and total.',
    status: 'implemented',
    phase: 9,
    channels: ['in_app', 'email', 'sms'],
    transactional: true,
    divisionId: 'TL-DIV-16-MARKETPLACE',
    category: 'marketplace',
  },
  {
    id: 'TL-NOTIF-ORDER-RECEIVED-001',
    name: 'Order activity for a seller',
    description: 'Tells a business’s administrators about a new order, a return request, or a buyer cancelling or receiving an order.',
    status: 'implemented',
    phase: 9,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-16-MARKETPLACE',
    category: 'marketplace',
  },
  {
    id: 'TL-NOTIF-ORDER-UPDATE-001',
    name: 'Your order',
    description: 'Tells a buyer the seller confirmed, declined, dispatched, cancelled or delivered their order, recorded a payment or refund, issued the invoice, or decided a return.',
    status: 'implemented',
    phase: 9,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-16-MARKETPLACE',
    category: 'marketplace',
  },
  {
    id: 'TL-NOTIF-SERVICE-CONTRACT-001',
    name: 'Maintenance contract activity',
    description: 'Tells a practice or a service business about a maintenance contract proposed, accepted, declined or cancelled, and service visits requested, scheduled or completed.',
    status: 'implemented',
    phase: 9,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-18-EQUIPMENT',
    category: 'marketplace',
  },
  {
    id: 'TL-NOTIF-EQUIPMENT-EXPIRY-001',
    name: 'Warranty or contract ending',
    description: 'Tells a practice’s administrators a warranty or maintenance contract ends within 30 days.',
    status: 'implemented',
    phase: 9,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-18-EQUIPMENT',
    category: 'marketplace',
  },
  {
    id: 'TL-NOTIF-MEMBERSHIP-001',
    name: 'Prime membership',
    description: 'Tells an organization’s administrators their Prime period started, renewed, could not renew (wallet short), or ended.',
    status: 'implemented',
    phase: 10,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-21-PRIME',
    category: 'billing',
  },
  {
    id: 'TL-NOTIF-ENTERPRISE-001',
    name: 'Enterprise agreement',
    description: 'Tells a group’s administrators their enterprise agreement was recorded or ended, and a member organization’s administrators that it joined or left the group.',
    status: 'implemented',
    phase: 12,
    channels: ['in_app', 'email'],
    transactional: true,
    divisionId: 'TL-DIV-32-ADMIN',
    category: 'account',
  },
] as const;

export const NOTIFICATION_BY_ID: ReadonlyMap<string, NotificationDefinition> = new Map(
  NOTIFICATIONS.map((n) => [n.id, n]),
);
