/**
 * TL-PAGE-FIND-001 — /find
 *
 * Generated by scripts/make-placeholder-pages.mjs.
 *
 * Deliberately not a mock-up. See src/components/shell/not-built-yet.tsx for
 * why a fake search box or placeholder article list is worse than an honest
 * empty page on a health platform.
 */

import type { Metadata } from 'next';
import { NotBuiltYet } from '@/components/shell/not-built-yet';

export const metadata: Metadata = {
  title: "Find a dentist",
  description: "Search for dentists and clinics near you by treatment, specialty, availability and distance.",
  // Not indexed while it has no content: an indexed empty page is a doorway
  // page, and it would rank for queries it cannot answer.
  robots: { index: false, follow: true },
};

export default function Page() {
  return (
    <NotBuiltYet
      title={"Find a dentist"}
      description={"Search for dentists and clinics by location, treatment, specialty, language, fee, rating and availability — with list and map views, and distance-based ranking that puts competence ahead of marketing spend."}
      phase={"Phase 4 — Discovery and Appointment Engine"}
      alternatives={[{"href":"/register?role=dentist","label":"List your practice"},{"href":"/register","label":"Create an account"}]}
    />
  );
}
