/**
 * TL-PAGE-KNOWLEDGE-001 — /knowledge
 *
 * Generated by scripts/make-placeholder-pages.mjs.
 *
 * Deliberately not a mock-up. See src/components/shell/not-built-yet.tsx for
 * why a fake search box or placeholder article list is worse than an honest
 * empty page on a health platform.
 */

import type { Metadata } from 'next';
import { NotBuiltYet } from '@/components/shell/not-built-yet';

export const metadata: Metadata = {
  title: "Dental knowledge",
  description: "Sourced, accurate explanations of dental conditions, treatments and procedures.",
  // Not indexed while it has no content: an indexed empty page is a doorway
  // page, and it would rank for queries it cannot answer.
  robots: { index: false, follow: true },
};

export default function Page() {
  return (
    <NotBuiltYet
      title={"Dental knowledge"}
      description={"Sourced explanations of dental conditions, treatments and procedures, written to be understood at the reader’s level and attributed to their clinical sources."}
      phase={"Phase 7 — Knowledge, Research and Community"}
      alternatives={[{"href":"/","label":"Back to home"}]}
    />
  );
}
