/**
 * TL-PAGE-FORDENTISTS-001 — /for-dentists
 *
 * Generated by scripts/make-placeholder-pages.mjs.
 *
 * Deliberately not a mock-up. See src/components/shell/not-built-yet.tsx for
 * why a fake search box or placeholder article list is worse than an honest
 * empty page on a health platform.
 */

import type { Metadata } from 'next';
import { NotBuiltYet } from '@/components/shell/not-built-yet';

export const metadata: Metadata = {
  title: "For dentists",
  description: "Be discovered by the patients who need you. Profile, verification, availability and appointments.",
  // Not indexed while it has no content: an indexed empty page is a doorway
  // page, and it would rank for queries it cannot answer.
  robots: { index: false, follow: true },
};

export default function Page() {
  return (
    <NotBuiltYet
      title={"For dentists"}
      description={"A verified professional profile, availability and appointment management, patient leads, reviews and practice analytics. Verification of dental registration is what makes a profile appear in patient search."}
      phase={"Phase 3 — Dentist and Clinic Ecosystem"}
      alternatives={[{"href":"/register?role=dentist","label":"Create a dentist account"},{"href":"/account/organizations/new","label":"Create an organization"}]}
    />
  );
}
