/**
 * Generate docs/architecture/DIVISIONS.md from the division registry.
 *
 * Generated rather than hand-written because a 35-row table maintained by hand
 * drifts from the registry within a week, and a document that contradicts the
 * code is worse than no document (Constitution P9).
 *
 * Usage:  npx tsx scripts/generate-division-docs.mts
 *         (or: node --experimental-strip-types scripts/generate-division-docs.mts)
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { DIVISIONS } from '../src/registry/divisions.ts';
import { MODULES } from '../src/registry/modules.ts';
import type { LifecycleStatus } from '../src/registry/types.ts';

const STATUS_ICON: Record<LifecycleStatus, string> = {
  implemented: '✅',
  prepared: '🟡',
  planned: '🔴',
  deprecated: '⚫',
};

const lines: string[] = [
  '# Toothlogy Division Map',
  '',
  '**Document ID:** `TL-DOC-DIVISIONS-001`',
  '**Generated from:** [`src/registry/divisions.ts`](../../src/registry/divisions.ts)',
  '',
  '> This file is generated by `scripts/generate-division-docs.mts`.',
  '> Edit the registry, then regenerate — do not edit this file by hand.',
  '',
  'A **division** is a top-level capability domain. It owns its data and is the',
  'sole writer of it; other divisions read through its service interface rather',
  "than writing its tables (Constitution P7, §8).",
  '',
  'Division numbers are permanent. A division is never renumbered, and a retired',
  "division's number is never reissued (Constitution P6).",
  '',
  '## Status',
  '',
  '| | Meaning |',
  '|---|---|',
  '| ✅ | Implemented — code exists, wired up, tested |',
  '| 🟡 | Prepared — contracts exist, no domain behaviour |',
  '| 🔴 | Planned — number and dependencies reserved only |',
  '',
];

// Summary counts, derived rather than typed.
const counts = DIVISIONS.reduce<Record<string, number>>((acc, d) => {
  acc[d.status] = (acc[d.status] ?? 0) + 1;
  return acc;
}, {});

lines.push(
  `**${DIVISIONS.length} divisions:** ` +
    `${counts.implemented ?? 0} implemented, ` +
    `${counts.prepared ?? 0} prepared, ` +
    `${counts.planned ?? 0} planned.`,
  '',
  '---',
  '',
  '## Overview',
  '',
  '| # | Division | Pillars | Phase | Status |',
  '|---|---|---|---|---|',
);

for (const d of DIVISIONS) {
  lines.push(
    `| ${d.number} | **${d.name}** | ${d.pillars.join(', ')} | ${d.phase} | ${STATUS_ICON[d.status]} |`,
  );
}

lines.push('', '---', '', '## Detail', '');

for (const d of DIVISIONS) {
  const modules = MODULES.filter((m) => m.divisionId === d.id);

  lines.push(
    `### ${d.number} — ${d.name}`,
    '',
    `\`${d.id}\` · ${STATUS_ICON[d.status]} ${d.status} · Phase ${d.phase} · Pillars: ${d.pillars.join(', ')}`,
    '',
    d.description,
    '',
    `**Owns:** ${d.owns.map((o) => `\`${o}\``).join(', ')}`,
    '',
  );

  if (d.dependsOn.length > 0) {
    const names = d.dependsOn.map((id) => {
      const dep = DIVISIONS.find((x) => x.id === id);
      return dep ? `${dep.number} ${dep.name}` : id;
    });
    lines.push(`**Depends on:** ${names.join(' · ')}`, '');
  } else {
    lines.push('**Depends on:** nothing — this is the root of the dependency graph.', '');
  }

  if (modules.length > 0) {
    lines.push('**Registered modules:**', '');
    for (const m of modules) {
      lines.push(`- ${STATUS_ICON[m.status]} \`${m.id}\` — ${m.name}`);
    }
    lines.push('');
  }
}

const target = resolve(process.cwd(), 'docs/architecture/DIVISIONS.md');
writeFileSync(target, `${lines.join('\n')}\n`, 'utf8');

console.log(`Wrote ${target} (${DIVISIONS.length} divisions, ${MODULES.length} modules).`);
