/**
 * TL-PAGE-HELP-001 — /help
 *
 * Generated by scripts/make-placeholder-pages.mjs.
 *
 * Deliberately not a mock-up. See src/components/shell/not-built-yet.tsx for
 * why a fake search box or placeholder article list is worse than an honest
 * empty page on a health platform.
 */

import type { Metadata } from 'next';
import { NotBuiltYet } from '@/components/shell/not-built-yet';

export const metadata: Metadata = {
  title: "Help centre",
  description: "Get help with your Toothlogy account.",
  // Not indexed while it has no content: an indexed empty page is a doorway
  // page, and it would rank for queries it cannot answer.
  robots: { index: false, follow: true },
};

export default function Page() {
  return (
    <NotBuiltYet
      title={"Help centre"}
      description={"Searchable help articles, support tickets with tracked resolution, and escalation paths for clinical and billing issues."}
      phase={"Phase 5 — Trust and Communication"}
      alternatives={[{"href":"/contact","label":"Contact us"}]}
    />
  );
}
